(function(g){var window=this;'use strict';var AQa=function(a,b){return g.Nb(a,b)},BQa=function(a,b){b=b instanceof g.Gc?b:g.Mc(b,/^data:image\//i.test(b));
a.src=g.Hc(b)},CQa=function(a){if(a instanceof g.Uh)return a;
if("function"==typeof a.Jg)return a.Jg(!1);if(g.Ka(a)){var b=0,c=new g.Uh;c.i=function(){for(;;){if(b>=a.length)throw g.$h;if(b in a)return a[b++];b++}};
c.next=c.i.bind(c);return c}throw Error("Not implemented");},DQa=function(a,b,c){if(g.Ka(a))try{g.Ab(a,b,c)}catch(d){if(d!==g.$h)throw d;
}else{a=CQa(a);try{for(;;)b.call(c,a.i(),void 0,a)}catch(d){if(d!==g.$h)throw d;}}},B6=function(a){g.lk(a,"zx",Math.floor(2147483648*Math.random()).toString(36)+Math.abs(Math.floor(2147483648*Math.random())^g.Pa()).toString(36));
return a},C6=function(a,b,c){Array.isArray(c)||(c=[String(c)]);
g.uk(a.l,b,c)},EQa=function(a,b){var c=[];
DQa(b,function(d){try{var e=g.mr.prototype.l.call(this,d,!0)}catch(f){if("Storage: Invalid value was encountered"==f)return;throw f;}void 0===e?c.push(d):g.lr(e)&&c.push(d)},a);
return c},FQa=function(a,b){EQa(a,b).forEach(function(c){g.mr.prototype.remove.call(this,c)},a)},GQa=function(a){if(a.U){if(a.U.locationOverrideToken)return{locationOverrideToken:a.U.locationOverrideToken};
if(null!=a.U.latitudeE7&&null!=a.U.longitudeE7)return{latitudeE7:a.U.latitudeE7,longitudeE7:a.U.longitudeE7}}return null},HQa=function(a,b){g.gb(a,b)||a.push(b)},D6=function(a){var b=0,c;
for(c in a)b++;return b},IQa=function(a){try{return g.C.JSON.parse(a)}catch(b){}a=String(a);
if(/^\s*$/.test(a)?0:/^[\],:{}\s\u2028\u2029]*$/.test(a.replace(/\\["\\\/bfnrtu]/g,"@").replace(/(?:"[^"\\\n\r\u2028\u2029\x00-\x08\x0a-\x1f]*"|true|false|null|-?\d+(?:\.\d*)?(?:[eE][+\-]?\d+)?)[\s\u2028\u2029]*(?=:|,|]|}|$)/g,"]").replace(/(?:^|:|,)(?:[\s\u2028\u2029]*\[)+/g,"")))try{return eval("("+a+")")}catch(b){}throw Error("Invalid JSON string: "+a);},E6=function(a){if(g.C.JSON)try{return g.C.JSON.parse(a)}catch(b){}return IQa(a)},JQa=function(a,b,c,d){var e=new g.dk(null,void 0);
a&&g.ek(e,a);b&&g.fk(e,b);c&&g.gk(e,c);d&&(e.J=d);return e},F6=function(a,b){g.Ru[a]=!0;
var c=g.Pu();c&&c.publish.apply(c,arguments);g.Ru[a]=!1},G6=function(a){this.name=this.id="";
this.clientName="UNKNOWN_INTERFACE";this.app="";this.type="REMOTE_CONTROL";this.obfuscatedGaiaId=this.avatar=this.username="";this.capabilities=new Set;this.experiments=new Set;this.theme="u";new g.bi;this.model=this.brand="";this.year=0;this.chipset=this.osVersion=this.os="";this.mdxDialServerType="MDX_DIAL_SERVER_TYPE_UNKNOWN";a&&(this.id=a.id||a.name,this.name=a.name,this.clientName=a.clientName?a.clientName.toUpperCase():"UNKNOWN_INTERFACE",this.app=a.app,this.type=a.type||"REMOTE_CONTROL",this.username=
a.user||"",this.avatar=a.userAvatarUri||"",this.obfuscatedGaiaId=a.obfuscatedGaiaId||"",this.theme=a.theme||"u",KQa(this,a.capabilities||""),LQa(this,a.experiments||""),this.brand=a.brand||"",this.model=a.model||"",this.year=a.year||0,this.os=a.os||"",this.osVersion=a.osVersion||"",this.chipset=a.chipset||"",this.mdxDialServerType=a.mdxDialServerType||"MDX_DIAL_SERVER_TYPE_UNKNOWN",a=a.deviceInfo)&&(a=JSON.parse(a),this.brand=a.brand||"",this.model=a.model||"",this.year=a.year||0,this.os=a.os||"",
this.osVersion=a.osVersion||"",this.chipset=a.chipset||"",this.clientName=a.clientName?a.clientName.toUpperCase():"UNKNOWN_INTERFACE",this.mdxDialServerType=a.mdxDialServerType||"MDX_DIAL_SERVER_TYPE_UNKNOWN")},KQa=function(a,b){a.capabilities.clear();
g.Io(b.split(","),g.Oa(AQa,MQa)).forEach(function(c){a.capabilities.add(c)})},LQa=function(a,b){a.experiments.clear();
b.split(",").forEach(function(c){a.experiments.add(c)})},H6=function(a){a=a||{};
this.name=a.name||"";this.id=a.id||a.screenId||"";this.token=a.token||a.loungeToken||"";this.uuid=a.uuid||a.dialId||"";this.idType=a.screenIdType||"normal"},I6=function(a,b){return!!b&&(a.id==b||a.uuid==b)},NQa=function(a){return{name:a.name,
screenId:a.id,loungeToken:a.token,dialId:a.uuid,screenIdType:a.idType}},OQa=function(a){return new H6(a)},PQa=function(a){return Array.isArray(a)?g.Pe(a,OQa):[]},J6=function(a){return a?'{name:"'+a.name+'",id:'+a.id.substr(0,6)+"..,token:"+((a.token?".."+a.token.slice(-6):"-")+",uuid:"+(a.uuid?".."+a.uuid.slice(-6):"-")+",idType:"+a.idType+"}"):"null"},K6=function(a){return Array.isArray(a)?"["+g.Pe(a,J6).join(",")+"]":"null"},L6=function(){return"xxxxxxxx-xxxx-4xxx-yxxx-xxxxxxxxxxxx".replace(/[xy]/g,
function(a){var b=16*Math.random()|0;
return("x"==a?b:b&3|8).toString(16)})},QQa=function(a){return g.Pe(a,function(b){return{key:b.id,
name:b.name}})},M6=function(a,b){return g.db(a,function(c){return c||b?!c!=!b?!1:c.id==b.id:!0})},N6=function(a,b){return g.db(a,function(c){return I6(c,b)})},RQa=function(){var a=(0,g.uz)();
a&&FQa(a,a.i.Jg(!0))},O6=function(){var a=g.xz("yt-remote-connected-devices")||[];
g.xb(a);return a},SQa=function(a){if(g.ib(a))return[];
var b=a[0].indexOf("#"),c=-1==b?a[0]:a[0].substring(0,b);return g.Pe(a,function(d,e){return 0==e?d:d.substring(c.length)})},TQa=function(a){g.wz("yt-remote-connected-devices",a,86400)},Q6=function(){if(P6)return P6;
var a=g.xz("yt-remote-device-id");a||(a=L6(),g.wz("yt-remote-device-id",a,31536E3));for(var b=O6(),c=1,d=a;g.gb(b,d);)c++,d=a+"#"+c;return P6=d},R6=function(){var a=O6(),b=Q6();
g.gb(a,b);g.Az()&&g.zb(a,b);a=SQa(a);if(g.ib(a))try{g.At("remote_sid")}catch(c){}else try{g.xt("remote_sid",a.join(","),-1)}catch(c){}},UQa=function(){return g.xz("yt-remote-session-browser-channel")},VQa=function(){return g.xz("yt-remote-local-screens")||[]},WQa=function(){g.wz("yt-remote-lounge-token-expiration",!0,86400)},XQa=function(a){5<a.length&&(a=a.slice(a.length-5));
var b=g.Pe(VQa(),function(d){return d.loungeToken}),c=g.Pe(a,function(d){return d.loungeToken});
g.ym(c,function(d){return!g.gb(b,d)})&&WQa();
g.wz("yt-remote-local-screens",a,31536E3)},YQa=function(a,b){g.wz("yt-remote-session-browser-channel",a);
g.wz("yt-remote-session-screen-id",b);a=O6();b=Q6();g.gb(a,b)||a.push(b);TQa(a);R6()},S6=function(a){a||(g.zz("yt-remote-session-screen-id"),g.zz("yt-remote-session-video-id"));
R6();a=O6();g.lb(a,Q6());TQa(a)},ZQa=function(){if(!T6){var a=g.wr();
a&&(T6=new g.gr(a))}},$Qa=function(){ZQa();
return T6?!!T6.get("yt-remote-use-staging-server"):!1},U6=function(){var a=window.navigator.userAgent.match(/Chrome\/([0-9]+)/);
return a?parseInt(a[1],10):0},aRa=function(a){return!!document.currentScript&&(-1!=document.currentScript.src.indexOf("?"+a)||-1!=document.currentScript.src.indexOf("&"+a))},bRa=function(){return"function"==typeof window.__onGCastApiAvailable?window.__onGCastApiAvailable:null},V6=function(a){a.length?cRa(a.shift(),function(){V6(a)}):W6()},dRa=function(a){return"chrome-extension://"+a+"/cast_sender.js"},cRa=function(a,b,c){var d=document.createElement("script");
d.onerror=b;c&&(d.onload=c);g.Cj(d,g.Vq(a));(document.head||document.documentElement).appendChild(d)},eRa=function(){var a=U6(),b=[];
if(1<a){var c=a-1;b.push("//www.gstatic.com/eureka/clank/"+a+"/cast_sender.js");b.push("//www.gstatic.com/eureka/clank/"+c+"/cast_sender.js")}return b},W6=function(){var a=bRa();
a&&a(!1,"No cast extension found")},X6=function(){if(fRa){var a=2,b=bRa(),c=function(){a--;
0==a&&b&&b(!0)};
window.__onGCastApiAvailable=c;cRa("//www.gstatic.com/cast/sdk/libs/sender/1.0/cast_framework.js",W6,c)}},gRa=function(){X6();
var a=eRa();a.push("//www.gstatic.com/eureka/clank/cast_sender.js");V6(a)},iRa=function(){X6();
var a=eRa();a.push.apply(a,g.v(hRa.map(dRa)));a.push("//www.gstatic.com/eureka/clank/cast_sender.js");V6(a)},Y6=function(a,b,c){g.G.call(this);
this.I=null!=c?(0,g.D)(a,c):a;this.Nf=b;this.C=(0,g.D)(this.OO,this);this.i=!1;this.l=0;this.u=this.Ib=null;this.B=[]},Z6=function(a,b,c){g.G.call(this);
this.B=null!=c?a.bind(c):a;this.Nf=b;this.u=null;this.i=!1;this.l=0;this.Ib=null},$6=function(a){a.Ib=g.kh(function(){a.Ib=null;
a.i&&!a.l&&(a.i=!1,$6(a))},a.Nf);
var b=a.u;a.u=null;a.B.apply(null,b)},a7=function(){},b7=function(a,b){if("function"!==typeof a)throw Error("Fn must not be null and must be a function");
return g.C.setTimeout(function(){a()},b)},d7=function(a){c7.dispatchEvent(new jRa(c7,a))},jRa=function(a,b){g.kf.call(this,"statevent",a);
this.stat=b},e7=function(a,b,c,d){this.i=a;
this.l=b;this.L=c;this.J=d||1;this.u=45E3;this.B=new g.vk(this);this.I=new g.jh;this.I.setInterval(250)},lRa=function(a,b,c){a.Os=1;
a.Hm=B6(b.clone());a.aq=c;a.C=!0;kRa(a,null)},f7=function(a,b,c,d,e){a.Os=1;
a.Hm=B6(b.clone());a.aq=null;a.C=c;e&&(a.WL=!1);kRa(a,d)},kRa=function(a,b){a.Es=Date.now();
g7(a);a.Vn=a.Hm.clone();C6(a.Vn,"t",a.J);a.tA=0;a.If=a.i.oC(a.i.uw()?b:null);0<a.kB&&(a.Bz=new Z6((0,g.D)(a.WM,a,a.If),a.kB));a.B.Ra(a.If,"readystatechange",a.PO);b=a.Do?g.Vb(a.Do):{};a.aq?(a.pA="POST",b["Content-Type"]="application/x-www-form-urlencoded",a.If.send(a.Vn,a.pA,a.aq,b)):(a.pA="GET",a.WL&&!g.lg&&(b.Connection="close"),a.If.send(a.Vn,a.pA,null,b));a.i.rj(1)},nRa=function(a,b){var c=a.tA,d=b.indexOf("\n",c);
if(-1==d)return h7;c=Number(b.substring(c,d));if(isNaN(c))return mRa;d+=1;if(d+c>b.length)return h7;b=b.substr(d,c);a.tA=d+c;return b},pRa=function(a,b){a.Es=Date.now();
g7(a);var c=b?window.location.hostname:"";a.Vn=a.Hm.clone();g.lk(a.Vn,"DOMAIN",c);g.lk(a.Vn,"t",a.J);try{a.Ij=new ActiveXObject("htmlfile")}catch(m){i7(a);a.Dm=7;d7(22);j7(a);return}var d="<html><body>";if(b){var e="";for(b=0;b<c.length;b++){var f=c.charAt(b);if("<"==f)f=e+"\\x3c";else if(">"==f)f=e+"\\x3e";else{if(f in k7)f=k7[f];else if(f in oRa)f=k7[f]=oRa[f];else{var h=f.charCodeAt(0);if(31<h&&127>h)var l=f;else{if(256>h){if(l="\\x",16>h||256<h)l+="0"}else l="\\u",4096>h&&(l+="0");l+=h.toString(16).toUpperCase()}f=
k7[f]=l}f=e+f}e=f}d+='<script>document.domain="'+e+'"\x3c/script>'}d+="</body></html>";c=g.kd(g.gc("b/12014412"),d);a.Ij.open();a.Ij.write(g.ed(c));a.Ij.close();a.Ij.parentWindow.m=(0,g.D)(a.aV,a);a.Ij.parentWindow.d=(0,g.D)(a.nL,a,!0);a.Ij.parentWindow.rpcClose=(0,g.D)(a.nL,a,!1);c=a.Ij.createElement("DIV");a.Ij.parentWindow.document.body.appendChild(c);d=g.Lc(a.Vn.toString());d=g.td(g.Hc(d));d=g.kd(g.gc("b/12014412"),'<iframe src="'+d+'"></iframe>');g.md(c,d);a.i.rj(1)},g7=function(a){a.JF=Date.now()+
a.u;
qRa(a,a.u)},qRa=function(a,b){if(null!=a.Vs)throw Error("WatchDog timer not null");
a.Vs=b7((0,g.D)(a.hV,a),b)},l7=function(a){a.Vs&&(g.C.clearTimeout(a.Vs),a.Vs=null)},j7=function(a){a.i.jf()||a.To||a.i.Yw(a)},i7=function(a){l7(a);
g.ef(a.Bz);a.Bz=null;a.I.stop();g.xk(a.B);if(a.If){var b=a.If;a.If=null;b.abort();b.dispose()}a.Ij&&(a.Ij=null)},m7=function(a,b){try{a.i.gL(a,b),a.i.rj(4)}catch(c){}},sRa=function(a,b,c,d,e){if(0==d)c(!1);
else{var f=e||0;d--;rRa(a,b,function(h){h?c(!0):g.C.setTimeout(function(){sRa(a,b,c,d,f)},f)})}},rRa=function(a,b,c){var d=new Image;
d.onload=function(){try{n7(d),c(!0)}catch(e){}};
d.onerror=function(){try{n7(d),c(!1)}catch(e){}};
d.onabort=function(){try{n7(d),c(!1)}catch(e){}};
d.ontimeout=function(){try{n7(d),c(!1)}catch(e){}};
g.C.setTimeout(function(){if(d.ontimeout)d.ontimeout()},b);
BQa(d,a)},n7=function(a){a.onload=null;
a.onerror=null;a.onabort=null;a.ontimeout=null},tRa=function(a){this.i=a;
this.l=new a7},uRa=function(a){var b=o7(a.i,a.Vt,"/mail/images/cleardot.gif");
B6(b);sRa(b.toString(),5E3,(0,g.D)(a.JP,a),3,2E3);a.rj(1)},q7=function(a){var b=a.i.L;
if(null!=b)d7(5),b?(d7(11),p7(a.i,a,!1)):(d7(12),p7(a.i,a,!0));else if(a.lh=new e7(a,void 0,void 0,void 0),a.lh.Do=a.lB,b=a.i,b=o7(b,b.uw()?a.Gt:null,a.mB),d7(5),!g.ie||g.ae(10))C6(b,"TYPE","xmlhttp"),f7(a.lh,b,!1,a.Gt,!1);else{C6(b,"TYPE","html");var c=a.lh;a=!!a.Gt;c.Os=3;c.Hm=B6(b.clone());pRa(c,a)}},r7=function(a,b,c){this.Pa=1;
this.i=[];this.u=[];this.B=new a7;this.J=a||null;this.L=null!=b?b:null;this.C=c||!1},vRa=function(a,b){this.i=a;
this.map=b;this.context=null},wRa=function(a,b,c,d){g.kf.call(this,"timingevent",a);
this.size=b;this.jw=d},xRa=function(a){g.kf.call(this,"serverreachability",a)},ARa=function(a){yRa(a);
if(3==a.Pa){var b=a.Dv++,c=a.Hx.clone();g.lk(c,"SID",a.l);g.lk(c,"RID",b);g.lk(c,"TYPE","terminate");s7(a,c);b=new e7(a,a.l,b,void 0);b.Os=2;b.Hm=B6(c.clone());BQa(new Image,b.Hm.toString());b.Es=Date.now();g7(b)}zRa(a)},BRa=function(a){a.kQ(1,0);
a.Hx=o7(a,null,a.nB);t7(a)},yRa=function(a){a.Mm&&(a.Mm.abort(),a.Mm=null);
a.De&&(a.De.cancel(),a.De=null);a.yl&&(g.C.clearTimeout(a.yl),a.yl=null);u7(a);a.Tg&&(a.Tg.cancel(),a.Tg=null);a.Vm&&(g.C.clearTimeout(a.Vm),a.Vm=null)},CRa=function(a,b){if(0==a.Pa)throw Error("Invalid operation: sending map when state is closed");
a.i.push(new vRa(a.TR++,b));2!=a.Pa&&3!=a.Pa||t7(a)},DRa=function(a){var b=0;
a.De&&b++;a.Tg&&b++;return b},t7=function(a){a.Tg||a.Vm||(a.Vm=b7((0,g.D)(a.lL,a),0),a.Cr=0)},FRa=function(a,b){if(1==a.Pa){if(!b){a.Dv=Math.floor(1E5*Math.random());
b=a.Dv++;var c=new e7(a,"",b,void 0);c.Do=a.Xj;var d=v7(a),e=a.Hx.clone();g.lk(e,"RID",b);g.lk(e,"CVER","1");s7(a,e);lRa(c,e,d);a.Tg=c;a.Pa=2}}else 3==a.Pa&&(b?ERa(a,b):0==a.i.length||a.Tg||ERa(a))},ERa=function(a,b){if(b)if(6<a.Uo){a.i=a.u.concat(a.i);
a.u.length=0;var c=a.Dv-1;b=v7(a)}else c=b.L,b=b.aq;else c=a.Dv++,b=v7(a);var d=a.Hx.clone();g.lk(d,"SID",a.l);g.lk(d,"RID",c);g.lk(d,"AID",a.Tr);s7(a,d);c=new e7(a,a.l,c,a.Cr+1);c.Do=a.Xj;c.setTimeout(1E4+Math.round(1E4*Math.random()));a.Tg=c;lRa(c,d,b)},s7=function(a,b){a.Jf&&(a=a.Jf.OI())&&g.Cb(a,function(c,d){g.lk(b,d,c)})},v7=function(a){var b=Math.min(a.i.length,1E3),c=["count="+b];
if(6<a.Uo&&0<b){var d=a.i[0].i;c.push("ofs="+d)}else d=0;for(var e={},f=0;f<b;e={Dq:e.Dq},f++){e.Dq=a.i[f].i;var h=a.i[f].map;e.Dq=6>=a.Uo?f:e.Dq-d;try{g.Cb(h,function(l){return function(m,n){c.push("req"+l.Dq+"_"+n+"="+encodeURIComponent(m))}}(e))}catch(l){c.push("req"+e.Dq+"_type="+encodeURIComponent("_badmap"))}}a.u=a.u.concat(a.i.splice(0,b));
return c.join("&")},GRa=function(a){a.De||a.yl||(a.I=1,a.yl=b7((0,g.D)(a.kL,a),0),a.dr=0)},w7=function(a){if(a.De||a.yl||3<=a.dr)return!1;
a.I++;a.yl=b7((0,g.D)(a.kL,a),HRa(a,a.dr));a.dr++;return!0},p7=function(a,b,c){a.nA=c;
a.Yj=b.bl;a.C||BRa(a)},u7=function(a){null!=a.fp&&(g.C.clearTimeout(a.fp),a.fp=null)},HRa=function(a,b){var c=5E3+Math.floor(1E4*Math.random());
a.isActive()||(c*=2);return c*b},x7=function(a,b){if(2==b||9==b){var c=null;
a.Jf&&(c=null);var d=(0,g.D)(a.dW,a);c||(c=new g.dk("//www.google.com/images/cleardot.gif"),B6(c));rRa(c.toString(),1E4,d)}else d7(2);IRa(a,b)},IRa=function(a,b){a.Pa=0;
a.Jf&&a.Jf.dI(b);zRa(a);yRa(a)},zRa=function(a){a.Pa=0;
a.Yj=-1;if(a.Jf)if(0==a.u.length&&0==a.i.length)a.Jf.bC();else{g.pb(a.u);var b=g.pb(a.i);a.u.length=0;a.i.length=0;a.Jf.bC(b)}},o7=function(a,b,c){var d=g.qk(c);
if(""!=d.i)b&&g.fk(d,b+"."+d.i),g.gk(d,d.u);else{var e=window.location;d=JQa(e.protocol,b?b+"."+e.hostname:e.hostname,+e.port,c)}a.Au&&g.Cb(a.Au,function(f,h){g.lk(d,h,f)});
g.lk(d,"VER",a.Uo);s7(a,d);return d},JRa=function(){},KRa=function(){this.i=[];
this.l=[]},LRa=function(a,b){this.action=a;
this.params=b||{}},y7=function(a,b){g.G.call(this);
this.i=new g.K(this.SU,0,this);g.J(this,this.i);this.Nf=5E3;this.l=0;if("function"===typeof a)b&&(a=(0,g.D)(a,b));else if(a&&"function"===typeof a.handleEvent)a=(0,g.D)(a.handleEvent,a);else throw Error("Invalid listener argument");this.u=a},z7=function(a,b,c,d,e){c=void 0===c?!1:c;
d=void 0===d?function(){return""}:d;
e=void 0===e?!1:e;this.xa=a;this.I=b;this.u=new g.fr;this.l=new y7(this.IV,this);this.i=null;this.Z=!1;this.C=null;this.U="";this.L=this.B=0;this.J=[];this.ya=c;this.ea=d;this.Aa=e},MRa=function(a){return{firstTestResults:[""],
secondTestResults:!a.i.nA,sessionId:a.i.l,arrayId:a.i.Tr}},NRa=function(a,b){a.L=b||0;
a.l.stop();A7(a);a.i&&(3==a.i.getState()&&FRa(a.i),ARa(a.i));a.L=0},B7=function(a){return!!a.i&&3==a.i.getState()},A7=function(a){if(a.i){var b=a.ea(),c=a.i.Xj||{};
b?c["x-youtube-lounge-xsrf-token"]=b:delete c["x-youtube-lounge-xsrf-token"];a.i.Xj=c}},C7=function(a){this.port=this.domain="";
this.i="/api/lounge";this.l=!0;a=a||document.location.href;var b=Number(g.hi(4,a))||"";b&&(this.port=":"+b);this.domain=g.ii(a)||"";a=g.Wc;0<=a.search("MSIE")&&(a=a.match(/MSIE ([\d.]+)/)[1],0>g.Ec(a,"10.0")&&(this.l=!1))},D7=function(a,b){var c=a.i;
a.l&&(c="https://"+a.domain+a.port+a.i);return g.ti(c+b,{})},E7=function(a,b,c,d,e){a={format:"JSON",
method:"POST",context:a,timeout:5E3,withCredentials:!1,onSuccess:g.Oa(a.B,d,!0),onError:g.Oa(a.u,e),onTimeout:g.Oa(a.C,e)};c&&(a.postParams=c,a.headers={"Content-Type":"application/x-www-form-urlencoded"});return g.lt(b,a)},RRa=function(){var a=ORa;
PRa();F7.push(a);QRa()},G7=function(a,b){PRa();
var c=SRa(a,String(b));g.ib(F7)?TRa(c):(QRa(),g.Ab(F7,function(d){d(c)}))},PRa=function(){F7||(F7=g.Ga("yt.mdx.remote.debug.handlers_")||[],g.Fa("yt.mdx.remote.debug.handlers_",F7,void 0))},TRa=function(a){var b=(H7+1)%50;
H7=b;I7[b]=a;J7||(J7=49==b)},QRa=function(){var a=F7;
if(I7[0]){var b=J7?H7:-1;do{b=(b+1)%50;var c=I7[b];g.Ab(a,function(d){d(c)})}while(b!=H7);
I7=Array(50);H7=-1;J7=!1}},SRa=function(a,b){var c=(Date.now()-URa)/1E3;
c.toFixed&&(c=c.toFixed(3));var d=[];d.push("[",c+"s","] ");d.push("[","yt.mdx.remote","] ");d.push(a+": "+b,"\n");return d.join("")},K7=function(a){g.R.call(this);
this.I=a;this.screens=[]},VRa=function(a,b){var c=a.get(b.uuid)||a.get(b.id);
if(c)return a=c.name,c.id=b.id||c.id,c.name=b.name,c.token=b.token,c.uuid=b.uuid||c.uuid,c.name!=a;a.screens.push(b);return!0},WRa=function(a,b){var c=a.screens.length!=b.length;
a.screens=g.Io(a.screens,function(f){return!!M6(b,f)});
for(var d=0,e=b.length;d<e;d++)c=VRa(a,b[d])||c;return c},XRa=function(a,b){var c=a.screens.length;
a.screens=g.Io(a.screens,function(d){return!(d||b?!d!=!b?0:d.id==b.id:1)});
return a.screens.length<c},L7=function(a,b,c,d,e){g.R.call(this);
this.u=a;this.J=b;this.B=c;this.I=d;this.C=e;this.l=0;this.i=null;this.Ib=NaN},N7=function(a){K7.call(this,"LocalScreenService");
this.l=a;this.i=NaN;M7(this);this.info("Initializing with "+K6(this.screens))},YRa=function(a){if(a.screens.length){var b=g.Pe(a.screens,function(d){return d.id}),c=D7(a.l,"/pairing/get_lounge_token_batch");
E7(a.l,c,{screen_ids:b.join(",")},(0,g.D)(a.JQ,a),(0,g.D)(a.IQ,a))}},M7=function(a){if(g.js("deprecate_pair_servlet_enabled"))return WRa(a,[]);
var b=PQa(VQa());b=g.Io(b,function(c){return!c.uuid});
return WRa(a,b)},O7=function(a,b){XQa(g.Pe(a.screens,NQa));
b&&WQa()},Q7=function(a,b){g.R.call(this);
this.I=b;b=(b=g.xz("yt-remote-online-screen-ids")||"")?b.split(","):[];for(var c={},d=this.I(),e=0,f=d.length;e<f;++e){var h=d[e].id;c[h]=g.gb(b,h)}this.i=c;this.C=a;this.u=this.B=NaN;this.l=null;P7("Initialized with "+g.Kh(this.i))},R7=function(a,b,c){var d=D7(a.C,"/pairing/get_screen_availability");
E7(a.C,d,{lounge_token:b.token},(0,g.D)(function(e){e=e.screens||[];for(var f=0,h=e.length;f<h;++f)if(e[f].loungeToken==b.token){c("online"==e[f].status);return}c(!1)},a),(0,g.D)(function(){c(!1)},a))},S7=function(a,b){a:if(D6(b)!=D6(a.i))var c=!1;
else{c=g.Lb(b);for(var d=0,e=c.length;d<e;++d)if(!a.i[c[d]]){c=!1;break a}c=!0}c||(P7("Updated online screens: "+g.Kh(a.i)),a.i=b,a.Y("screenChange"));ZRa(a)},T7=function(a){isNaN(a.u)||g.gt(a.u);
a.u=g.et((0,g.D)(a.FE,a),0<a.B&&a.B<g.Pa()?2E4:1E4)},P7=function(a){G7("OnlineScreenService",a)},$Ra=function(a){var b={};
g.Ab(a.I(),function(c){c.token?b[c.token]=c.id:this.Zd("Requesting availability of screen w/o lounge token.")});
return b},ZRa=function(a){a=g.Lb(g.Db(a.i,function(b){return b}));
g.xb(a);a.length?g.wz("yt-remote-online-screen-ids",a.join(","),60):g.zz("yt-remote-online-screen-ids")},U7=function(a,b){b=void 0===b?!1:b;
K7.call(this,"ScreenService");this.B=a;this.J=b;this.i=this.l=null;this.u=[];this.C={};aSa(this)},cSa=function(a,b,c,d,e,f){a.info("getAutomaticScreenByIds "+c+" / "+b);
c||(c=a.C[b]);var h=a.Gh(),l=c?N6(h,c):null;c&&(a.J||l)||(l=N6(h,b));if(l){l.uuid=b;var m=V7(a,l);R7(a.i,m,function(n){e(n?m:null)})}else c?bSa(a,c,(0,g.D)(function(n){var p=V7(this,new H6({name:d,
screenId:c,loungeToken:n,dialId:b||""}));R7(this.i,p,function(q){e(q?p:null)})},a),f):e(null)},dSa=function(a,b){for(var c=0,d=a.screens.length;c<d;++c)if(a.screens[c].name==b)return a.screens[c];
return null},eSa=function(a,b,c){R7(a.i,b,c)},bSa=function(a,b,c,d){a.info("requestLoungeToken_ for "+b);
var e={postParams:{screen_ids:b},method:"POST",context:a,onSuccess:function(f,h){f=h&&h.screens||[];f[0]&&f[0].screenId==b?c(f[0].loungeToken):d(Error("Missing lounge token in token response"))},
onError:function(){d(Error("Request screen lounge token failed"))}};
g.lt(D7(a.B,"/pairing/get_lounge_token_batch"),e)},fSa=function(a){a.screens=a.l.Gh();
var b=a.C,c={},d;for(d in b)c[b[d]]=d;b=0;for(d=a.screens.length;b<d;++b){var e=a.screens[b];e.uuid=c[e.id]||""}a.info("Updated manual screens: "+K6(a.screens))},aSa=function(a){W7(a);
a.l=new N7(a.B);a.l.subscribe("screenChange",(0,g.D)(a.SQ,a));fSa(a);a.J||(a.u=PQa(g.xz("yt-remote-automatic-screen-cache")||[]));W7(a);a.info("Initializing automatic screens: "+K6(a.u));a.i=new Q7(a.B,(0,g.D)(a.Gh,a,!0));a.i.subscribe("screenChange",(0,g.D)(function(){this.Y("onlineScreenChange")},a))},V7=function(a,b){var c=a.get(b.id);
c?(c.uuid=b.uuid,b=c):((c=N6(a.u,b.uuid))?(c.id=b.id,c.token=b.token,b=c):a.u.push(b),a.J||gSa(a));W7(a);a.C[b.uuid]=b.id;g.wz("yt-remote-device-id-map",a.C,31536E3);return b},gSa=function(a){a=g.Io(a.u,function(b){return"shortLived"!=b.idType});
g.wz("yt-remote-automatic-screen-cache",g.Pe(a,NQa))},W7=function(a){a.C=g.xz("yt-remote-device-id-map")||{}},X7=function(a,b,c){g.R.call(this);
this.Aa=c;this.u=a;this.i=b;this.B=null},Y7=function(a,b){a.B=b;
a.Y("sessionScreen",a.B)},hSa=function(a,b){a.B&&(a.B.token=b,V7(a.u,a.B));
a.Y("sessionScreen",a.B)},Z7=function(a,b){G7(a.Aa,b)},$7=function(a,b,c){X7.call(this,a,b,"CastSession");
var d=this;this.config_=c;this.l=null;this.ea=(0,g.D)(this.UO,this);this.ya=(0,g.D)(this.kV,this);this.Z=g.et(function(){iSa(d,null)},12E4);
this.J=this.C=this.I=this.L=0;this.xa=!1;this.U="unknown"},a8=function(a,b){g.gt(a.J);
a.J=0;0==b?jSa(a):a.J=g.et(function(){jSa(a)},b)},jSa=function(a){kSa(a,"getLoungeToken");
g.gt(a.C);a.C=g.et(function(){lSa(a,null)},3E4)},kSa=function(a,b){a.info("sendYoutubeMessage_: "+b+" "+g.Kh(void 0));
var c={};c.type=b;a.l?a.l.sendMessage("urn:x-cast:com.google.youtube.mdx",c,g.Ha,(0,g.D)(function(){Z7(this,"Failed to send message: "+b+".")},a)):Z7(a,"Sending yt message without session: "+g.Kh(c))},b8=function(a,b){b?(a.info("onConnectedScreenId_: Received screenId: "+b),a.getScreen()&&a.getScreen().id==b||a.cJ(b,function(c){Y7(a,c)},function(){return a.qg()},5)):a.qg(Error("Waiting for session status timed out."))},nSa=function(a,b,c){a.info("onConnectedScreenData_: Received screenData: "+JSON.stringify(b));
var d=new H6(b);mSa(a,d,function(e){e?(a.xa=!0,V7(a.u,d),Y7(a,d),a.U="unknown",a8(a,c)):(g.os(Error("CastSession, RemoteScreen from screenData: "+JSON.stringify(b)+" is not online.")),a.qg())},5)},iSa=function(a,b){g.gt(a.Z);
a.Z=0;b?a.config_.enableCastLoungeToken&&b.loungeToken?b.deviceId?a.getScreen()&&a.getScreen().uuid==b.deviceId||(b.loungeTokenRefreshIntervalMs?nSa(a,{name:a.i.friendlyName,screenId:b.screenId,loungeToken:b.loungeToken,dialId:b.deviceId,screenIdType:"shortLived"},b.loungeTokenRefreshIntervalMs):(g.os(Error("No loungeTokenRefreshIntervalMs presents in mdxSessionStatusData: "+JSON.stringify(b)+".")),b8(a,b.screenId))):(g.os(Error("No device id presents in mdxSessionStatusData: "+JSON.stringify(b)+
".")),b8(a,b.screenId)):b8(a,b.screenId):a.qg(Error("Waiting for session status timed out."))},lSa=function(a,b){g.gt(a.C);
a.C=0;var c=null;if(b)if(b.loungeToken){var d;(null==(d=a.getScreen())?void 0:d.token)==b.loungeToken&&(c="staleLoungeToken")}else c="missingLoungeToken";else c="noLoungeTokenResponse";c?(a.info("Did not receive a new lounge token in onLoungeToken_ with data: "+(JSON.stringify(b)+", error: "+c)),a.U=c,a8(a,3E4)):(hSa(a,b.loungeToken),a.xa=!1,a.U="unknown",a8(a,b.loungeTokenRefreshIntervalMs))},mSa=function(a,b,c,d){g.gt(a.I);
a.I=0;eSa(a.u,b,function(e){e||0>d?c(e):a.I=g.et(function(){mSa(a,b,c,d-1)},300)})},oSa=function(a){g.gt(a.L);
a.L=0;g.gt(a.I);a.I=0;g.gt(a.Z);a.Z=0;g.gt(a.C);a.C=0;g.gt(a.J);a.J=0},c8=function(a,b,c,d){X7.call(this,a,b,"DialSession");
this.config_=d;this.l=this.L=null;this.ya="";this.Ia=c;this.Ja=null;this.Z=g.Ha;this.U=NaN;this.Fa=(0,g.D)(this.VO,this);this.C=g.Ha;this.J=this.I=0;this.ea=!1;this.xa="unknown"},d8=function(a){var b;
return!!(a.config_.enableDialLoungeToken&&(null==(b=a.l)?0:b.getDialAppInfo))},pSa=function(a){a.C=a.u.IG(a.ya,a.i.label,a.i.friendlyName,d8(a),function(b,c){a.C=g.Ha;
a.ea=!0;Y7(a,b);"shortLived"==b.idType&&0<c&&e8(a,c)},function(b){a.C=g.Ha;
a.qg(b)})},qSa=function(a){var b={};
b.pairingCode=a.ya;b.theme=a.Ia;$Qa()&&(b.env_useStageMdx=1);return g.ri(b)},f8=function(a){return new Promise(function(b){a.ya=L6();
if(a.Ja){var c=new chrome.cast.DialLaunchResponse(!0,qSa(a));b(c);pSa(a)}else a.Z=function(){g.gt(a.U);a.Z=function(){};
a.U=NaN;var d=new chrome.cast.DialLaunchResponse(!0,qSa(a));b(d);pSa(a)},a.U=g.et(function(){a.Z()},100)})},sSa=function(a,b,c){a.info("initOnConnectedScreenDataPromise_: Received screenData: "+JSON.stringify(b));
var d=new H6(b);return(new Promise(function(e){rSa(a,d,function(f){f?(a.ea=!0,V7(a.u,d),Y7(a,d),e8(a,c)):g.os(Error("DialSession, RemoteScreen from screenData: "+JSON.stringify(b)+" is not online."));e(f)},5)})).then(function(e){return e?new chrome.cast.DialLaunchResponse(!1):f8(a)})},tSa=function(a,b){var c=a.L.receiver.label,d=a.i.friendlyName;
return(new Promise(function(e){cSa(a.u,c,b,d,function(f){f&&f.token&&Y7(a,f);e(f)},function(f){Z7(a,"Failed to get DIAL screen: "+f);
e(null)})})).then(function(e){return e&&e.token?new chrome.cast.DialLaunchResponse(!1):f8(a)})},rSa=function(a,b,c,d){g.gt(a.I);
a.I=0;eSa(a.u,b,function(e){e||0>d?c(e):a.I=g.et(function(){rSa(a,b,c,d-1)},300)})},e8=function(a,b){a.info("getDialAppInfoWithTimeout_ "+b);
d8(a)&&(g.gt(a.J),a.J=0,0==b?uSa(a):a.J=g.et(function(){uSa(a)},b))},uSa=function(a){d8(a)&&a.l.getDialAppInfo(function(b){a.info("getDialAppInfo dialLaunchData: "+JSON.stringify(b));
b=b.extraData||{};var c=null;if(b.loungeToken){var d;(null==(d=a.getScreen())?void 0:d.token)==b.loungeToken&&(c="staleLoungeToken")}else c="missingLoungeToken";c?(a.xa=c,e8(a,3E4)):(a.ea=!1,a.xa="unknown",hSa(a,b.loungeToken),e8(a,b.loungeTokenRefreshIntervalMs))},function(b){a.info("getDialAppInfo error: "+b);
a.xa="noLoungeTokenResponse";e8(a,3E4)})},vSa=function(a){g.gt(a.I);
a.I=0;g.gt(a.J);a.J=0;a.C();a.C=function(){};
g.gt(a.U)},g8=function(a,b){X7.call(this,a,b,"ManualSession");
this.l=g.et((0,g.D)(this.Ur,this,null),150)},h8=function(a,b){g.R.call(this);
this.config_=b;this.l=a;this.L=b.appId||"233637DE";this.B=b.theme||"cl";this.U=b.disableCastApi||!1;this.I=b.forceMirroring||!1;this.i=null;this.J=!1;this.u=[];this.C=(0,g.D)(this.gU,this)},wSa=function(a,b){return b?g.db(a.u,function(c){return I6(b,c.label)},a):null},i8=function(a){G7("Controller",a)},ORa=function(a){window.chrome&&chrome.cast&&chrome.cast.logMessage&&chrome.cast.logMessage(a)},j8=function(a){return a.J||!!a.u.length||!!a.i},k8=function(a,b,c){b!=a.i&&(g.ef(a.i),(a.i=b)?(c?a.Y("yt-remote-cast2-receiver-resumed",
b.i):a.Y("yt-remote-cast2-receiver-selected",b.i),b.subscribe("sessionScreen",(0,g.D)(a.jL,a,b)),b.subscribe("sessionFailed",function(){return xSa(a,b)}),b.getScreen()?a.Y("yt-remote-cast2-session-change",b.getScreen()):c&&a.i.Ur(null)):a.Y("yt-remote-cast2-session-change",null))},xSa=function(a,b){a.i==b&&a.Y("yt-remote-cast2-session-failed")},ySa=function(a){var b=a.l.HG(),c=a.i&&a.i.i;
a=g.Pe(b,function(d){c&&I6(d,c.label)&&(c=null);var e=d.uuid?d.uuid:d.id,f=wSa(this,d);f?(f.label=e,f.friendlyName=d.name):(f=new chrome.cast.Receiver(e,d.name),f.receiverType=chrome.cast.ReceiverType.CUSTOM);return f},a);
c&&(c.receiverType!=chrome.cast.ReceiverType.CUSTOM&&(c=new chrome.cast.Receiver(c.label,c.friendlyName),c.receiverType=chrome.cast.ReceiverType.CUSTOM),a.push(c));return a},DSa=function(a,b,c,d){d.disableCastApi?l8("Cannot initialize because disabled by Mdx config."):zSa()?ASa(b,d)&&(m8(!0),window.chrome&&chrome.cast&&chrome.cast.isAvailable?BSa(a,c):(window.__onGCastApiAvailable=function(e,f){e?BSa(a,c):(n8("Failed to load cast API: "+f),o8(!1),m8(!1),g.zz("yt-remote-cast-available"),g.zz("yt-remote-cast-receiver"),
CSa(),c(!1))},d.loadCastApiSetupScript?g.Bz("https://www.gstatic.com/cv/js/sender/v1/cast_sender.js"):0<=window.navigator.userAgent.indexOf("Android")&&0<=window.navigator.userAgent.indexOf("Chrome/")&&window.navigator.presentation?60<=U6()&&gRa():!window.chrome||!window.navigator.presentation||0<=window.navigator.userAgent.indexOf("Edge")?W6():89<=U6()?iRa():(X6(),V6(hRa.map(dRa))))):l8("Cannot initialize because not running Chrome")},CSa=function(){l8("dispose");
var a=p8();a&&a.dispose();g.Fa("yt.mdx.remote.cloudview.instance_",null,void 0);ESa(!1);g.Uu(q8);q8.length=0},r8=function(){return!!g.xz("yt-remote-cast-installed")},FSa=function(){var a=g.xz("yt-remote-cast-receiver");
return a?a.friendlyName:null},GSa=function(){l8("clearCurrentReceiver");
g.zz("yt-remote-cast-receiver")},HSa=function(){return r8()?p8()?p8().getCastSession():(n8("getCastSelector: Cast is not initialized."),null):(n8("getCastSelector: Cast API is not installed!"),null)},t8=function(){r8()?p8()?s8()?(l8("Requesting cast selector."),p8().requestSession()):(l8("Wait for cast API to be ready to request the session."),q8.push(g.Tu("yt-remote-cast2-api-ready",t8))):n8("requestCastSelector: Cast is not initialized."):n8("requestCastSelector: Cast API is not installed!")},u8=
function(a,b){s8()?p8().setConnectedScreenStatus(a,b):n8("setConnectedScreenStatus called before ready.")},zSa=function(){var a=0<=g.Wc.search(/ (CrMo|Chrome|CriOS)\//);
return g.bj||a},ISa=function(a,b){p8().init(a,b)},ASa=function(a,b){var c=!1;
p8()||(a=new h8(a,b),a.subscribe("yt-remote-cast2-availability-change",function(d){g.wz("yt-remote-cast-available",d);F6("yt-remote-cast2-availability-change",d)}),a.subscribe("yt-remote-cast2-receiver-selected",function(d){l8("onReceiverSelected: "+d.friendlyName);
g.wz("yt-remote-cast-receiver",d);F6("yt-remote-cast2-receiver-selected",d)}),a.subscribe("yt-remote-cast2-receiver-resumed",function(d){l8("onReceiverResumed: "+d.friendlyName);
g.wz("yt-remote-cast-receiver",d);F6("yt-remote-cast2-receiver-resumed",d)}),a.subscribe("yt-remote-cast2-session-change",function(d){l8("onSessionChange: "+J6(d));
d||g.zz("yt-remote-cast-receiver");F6("yt-remote-cast2-session-change",d)}),g.Fa("yt.mdx.remote.cloudview.instance_",a,void 0),c=!0);
l8("cloudview.createSingleton_: "+c);return c},p8=function(){return g.Ga("yt.mdx.remote.cloudview.instance_")},BSa=function(a,b){o8(!0);
m8(!1);ISa(a,function(c){c?(ESa(!0),g.Vu("yt-remote-cast2-api-ready")):(n8("Failed to initialize cast API."),o8(!1),g.zz("yt-remote-cast-available"),g.zz("yt-remote-cast-receiver"),CSa());b(c)})},l8=function(a){G7("cloudview",a)},n8=function(a){G7("cloudview",a)},o8=function(a){l8("setCastInstalled_ "+a);
g.wz("yt-remote-cast-installed",a)},s8=function(){return!!g.Ga("yt.mdx.remote.cloudview.apiReady_")},ESa=function(a){l8("setApiReady_ "+a);
g.Fa("yt.mdx.remote.cloudview.apiReady_",a,void 0)},m8=function(a){g.Fa("yt.mdx.remote.cloudview.initializing_",a,void 0)},v8=function(a){this.index=-1;
this.videoId=this.listId="";this.volume=this.playerState=-1;this.muted=!1;this.audioTrackId=null;this.I=this.J=0;this.trackData=null;this.hasNext=this.Ak=!1;this.L=this.C=this.i=this.B=0;this.u=NaN;this.l=!1;this.reset(a)},w8=function(a){a.audioTrackId=null;
a.trackData=null;a.playerState=-1;a.Ak=!1;a.hasNext=!1;a.J=0;a.I=g.Pa();a.B=0;a.i=0;a.C=0;a.L=0;a.u=NaN;a.l=!1},x8=function(a){return a.yc()?(g.Pa()-a.I)/1E3:0},y8=function(a,b){a.J=b;
a.I=g.Pa()},z8=function(a){switch(a.playerState){case 1:case 1081:return(g.Pa()-a.I)/1E3+a.J;
case -1E3:return 0}return a.J},A8=function(a,b,c){var d=a.videoId;
a.videoId=b;a.index=c;b!=d&&w8(a)},B8=function(a){var b={};
b.index=a.index;b.listId=a.listId;b.videoId=a.videoId;b.playerState=a.playerState;b.volume=a.volume;b.muted=a.muted;b.audioTrackId=a.audioTrackId;b.trackData=g.Wb(a.trackData);b.hasPrevious=a.Ak;b.hasNext=a.hasNext;b.playerTime=a.J;b.playerTimeAt=a.I;b.seekableStart=a.B;b.seekableEnd=a.i;b.duration=a.C;b.loadedTime=a.L;b.liveIngestionTime=a.u;return b},D8=function(a,b){g.R.call(this);
this.Pa=0;this.u=a;this.C=[];this.B=new KRa;this.l=this.i=null;this.L=(0,g.D)(this.DS,this);this.I=(0,g.D)(this.Lv,this);this.J=(0,g.D)(this.CS,this);this.U=(0,g.D)(this.LS,this);var c=0;a?(c=a.getProxyState(),3!=c&&(a.subscribe("proxyStateChange",this.VE,this),JSa(this))):c=3;0!=c&&(b?this.VE(c):g.et((0,g.D)(function(){this.VE(c)},this),0));
(a=HSa())&&C8(this,a);this.subscribe("yt-remote-cast2-session-change",this.U)},E8=function(a){return new v8(a.u.getPlayerContextData())},JSa=function(a){g.Ab("nowAutoplaying autoplayDismissed remotePlayerChange remoteQueueChange autoplayModeChange autoplayUpNext previousNextChange multiStateLoopEnabled".split(" "),function(b){this.C.push(this.u.subscribe(b,g.Oa(this.dU,b),this))},a)},KSa=function(a){g.Ab(a.C,function(b){this.u.unsubscribeByKey(b)},a);
a.C.length=0},F8=function(a){return 1==a.getState()},G8=function(a,b){var c=a.B;
50>c.i.length+c.l.length&&a.B.l.push(b)},I8=function(a,b,c){var d=E8(a);
y8(d,c);-1E3!=d.playerState&&(d.playerState=b);H8(a,d)},J8=function(a,b,c){a.u.sendMessage(b,c)},H8=function(a,b){KSa(a);
a.u.setPlayerContextData(B8(b));JSa(a)},C8=function(a,b){a.l&&(a.l.removeUpdateListener(a.L),a.l.removeMediaListener(a.I),a.Lv(null));
a.l=b;a.l&&(G7("CP","Setting cast session: "+a.l.sessionId),a.l.addUpdateListener(a.L),a.l.addMediaListener(a.I),a.l.media.length&&a.Lv(a.l.media[0]))},LSa=function(a){var b=a.i.media,c=a.i.customData;
if(b&&c){var d=E8(a);b.contentId!=d.videoId&&G7("CP","Cast changing video to: "+b.contentId);d.videoId=b.contentId;d.playerState=c.playerState;y8(d,a.i.getEstimatedTime());H8(a,d)}else G7("CP","No cast media video. Ignoring state update.")},K8=function(a,b,c){return(0,g.D)(function(d){this.Zd("Failed to "+b+" with cast v2 channel. Error code: "+d.code);
d.code!=chrome.cast.ErrorCode.TIMEOUT&&(this.Zd("Retrying "+b+" using MDx browser channel."),J8(this,b,c))},a)},L8=function(a,b,c,d){d=void 0===d?!1:d;
g.R.call(this);this.C=NaN;this.xa=!1;this.L=this.J=this.Z=this.ea=NaN;this.U=[];this.B=this.I=this.u=this.hc=this.i=null;this.Fa=a;this.Aa=d;this.U.push(g.ku(window,"beforeunload",(0,g.D)(this.EQ,this)));this.l=[];this.hc=new v8;this.Ja=b.id;this.ya=b.idType;this.i=MSa(this,c);this.i.subscribe("handlerOpened",this.IS,this);this.i.subscribe("handlerClosed",this.ES,this);this.i.subscribe("handlerError",this.GS,this);this.i.subscribe("handlerMessage",this.HS,this);this.i.Pz(b.token);this.subscribe("remoteQueueChange",
function(){var e=this.hc.videoId;g.Az()&&g.wz("yt-remote-session-video-id",e)},this)},NSa=function(a){return g.db(a.l,function(b){return"LOUNGE_SCREEN"==b.type})},M8=function(a){G7("conn",a)},MSa=function(a,b){return new z7(D7(a.Fa,"/bc"),b,!1,function(){return a.MG()},"shortLived"==a.ya)},N8=function(a,b){a.Y("proxyStateChange",b)},OSa=function(a){a.C=g.et((0,g.D)(function(){M8("Connecting timeout");
this.yr(1)},a),2E4)},O8=function(a){g.gt(a.C);
a.C=NaN},P8=function(a){g.gt(a.ea);
a.ea=NaN},PSa=function(a){Q8(a);
a.Z=g.et((0,g.D)(function(){R8(this,"getNowPlaying")},a),2E4)},Q8=function(a){g.gt(a.Z);
a.Z=NaN},RSa=function(a,b){var c=null;
if(b){var d=NSa(a);d&&(c={clientName:d.clientName,deviceMake:d.brand,deviceModel:d.model,osVersion:d.osVersion})}g.Fa("yt.mdx.remote.remoteClient_",c,void 0);b&&(O8(a),P8(a));c=B7(a.i)&&isNaN(a.C);b==c?b&&(N8(a,1),R8(a,"getSubtitlesTrack")):b?(a.bJ()&&a.hc.reset(),N8(a,1),R8(a,"getNowPlaying"),QSa(a)):a.yr(1)},SSa=function(a,b){var c=b.params.videoId;
delete b.params.videoId;c==a.hc.videoId&&(g.Rb(b.params)?a.hc.trackData=null:a.hc.trackData=b.params,a.Y("remotePlayerChange"))},TSa=function(a,b){var c=b.params.videoId||b.params.video_id,d=parseInt(b.params.currentIndex,10);
a.hc.listId=b.params.listId||a.hc.listId;A8(a.hc,c,d);a.Y("remoteQueueChange")},VSa=function(a,b){b.params=b.params||{};
TSa(a,b);USa(a,b);a.Y("autoplayDismissed")},USa=function(a,b){var c=parseInt(b.params.currentTime||b.params.current_time,10);
y8(a.hc,isNaN(c)?0:c);c=parseInt(b.params.state,10);c=isNaN(c)?-1:c;-1==c&&-1E3==a.hc.playerState&&(c=-1E3);a.hc.playerState=c;c=Number(b.params.loadedTime);a.hc.L=isNaN(c)?0:c;a.hc.Cj(Number(b.params.duration));c=a.hc;var d=Number(b.params.liveIngestionTime);c.u=d;c.l=isNaN(d)?!1:!0;c=a.hc;d=Number(b.params.seekableStartTime);b=Number(b.params.seekableEndTime);c.B=isNaN(d)?0:d;c.i=isNaN(b)?0:b;1==a.hc.playerState?PSa(a):Q8(a);a.Y("remotePlayerChange")},WSa=function(a,b){if(-1E3!=a.hc.playerState){var c=
1085;
switch(parseInt(b.params.adState,10)){case 1:c=1081;break;case 2:c=1084;break;case 0:c=1083}a.hc.playerState=c;b=parseInt(b.params.currentTime,10);y8(a.hc,isNaN(b)?0:b);a.Y("remotePlayerChange")}},XSa=function(a,b){var c="true"==b.params.muted;
a.hc.volume=parseInt(b.params.volume,10);a.hc.muted=c;a.Y("remotePlayerChange")},YSa=function(a,b){a.I=b.params.videoId;
a.Y("nowAutoplaying",parseInt(b.params.timeout,10))},ZSa=function(a,b){var c="true"==b.params.hasNext;
a.hc.Ak="true"==b.params.hasPrevious;a.hc.hasNext=c;a.Y("previousNextChange")},QSa=function(a){g.gt(a.L);
a.L=g.et((0,g.D)(a.yr,a,1),864E5)},R8=function(a,b,c){c?M8("Sending: action="+b+", params="+g.Kh(c)):M8("Sending: action="+b);
a.i.sendMessage(b,c)},S8=function(a){K7.call(this,"ScreenServiceProxy");
this.Me=a;this.i=[];this.i.push(this.Me.$_s("screenChange",(0,g.D)(this.ZO,this)));this.i.push(this.Me.$_s("onlineScreenChange",(0,g.D)(this.HT,this)))},cTa=function(a,b){ZQa();
if(!T6||!T6.get("yt-remote-disable-remote-module-for-dev")){b=g.O("MDX_CONFIG")||b;RQa();R6();T8||(T8=new C7(b?b.loungeApiHost:void 0),$Qa()&&(T8.i="/api/loungedev"));U8||(U8=g.Ga("yt.mdx.remote.deferredProxies_")||[],g.Fa("yt.mdx.remote.deferredProxies_",U8,void 0));$Sa();var c=V8();if(!c){var d=new U7(T8,b?b.disableAutomaticScreenCache||!1:!1);g.Fa("yt.mdx.remote.screenService_",d,void 0);c=V8();var e={};b&&(e={appId:b.appId,disableDial:b.disableDial,theme:b.theme,loadCastApiSetupScript:b.loadCastApiSetupScript,
disableCastApi:b.disableCastApi,enableDialLoungeToken:b.enableDialLoungeToken,enableCastLoungeToken:b.enableCastLoungeToken,forceMirroring:b.forceMirroring});g.Fa("yt.mdx.remote.enableConnectWithInitialState_",b?b.enableConnectWithInitialState||!1:!1,void 0);DSa(a,d,function(f){f?W8()&&u8(W8(),"YouTube TV"):d.subscribe("onlineScreenChange",function(){F6("yt-remote-receiver-availability-change")})},e)}b&&!g.Ga("yt.mdx.remote.initialized_")&&(g.Fa("yt.mdx.remote.initialized_",!0,void 0),X8("Initializing: "+
g.Kh(b)),Y8.push(g.Tu("yt-remote-cast2-api-ready",function(){F6("yt-remote-api-ready")})),Y8.push(g.Tu("yt-remote-cast2-availability-change",function(){F6("yt-remote-receiver-availability-change")})),Y8.push(g.Tu("yt-remote-cast2-receiver-selected",function(){Z8(null);
F6("yt-remote-auto-connect","cast-selector-receiver")})),Y8.push(g.Tu("yt-remote-cast2-receiver-resumed",function(){F6("yt-remote-receiver-resumed","cast-selector-receiver")})),Y8.push(g.Tu("yt-remote-cast2-session-change",aTa)),Y8.push(g.Tu("yt-remote-connection-change",function(f){f?u8(W8(),"YouTube TV"):$8()||(u8(null,null),GSa())})),Y8.push(g.Tu("yt-remote-cast2-session-failed",function(){F6("yt-remote-connection-failed")})),a=a9(),b.isAuto&&(a.id+="#dial"),e=b.capabilities||[],g.js("desktop_enable_autoplay")&&
e.push("atp"),0<e.length&&(a.capabilities=e),a.name=b.device,a.app=b.app,(b=b.theme)&&(a.theme=b),X8(" -- with channel params: "+g.Kh(a)),a?(g.wz("yt-remote-session-app",a.app),g.wz("yt-remote-session-name",a.name)):(g.zz("yt-remote-session-app"),g.zz("yt-remote-session-name")),g.Fa("yt.mdx.remote.channelParams_",a,void 0),c.start(),W8()||bTa())}},dTa=function(){var a=V8().Me.$_gos();
var b=b9();b&&c9()&&(M6(a,b)||a.push(b));return QQa(a)},d9=function(){var a=eTa();
!a&&r8()&&FSa()&&(a={key:"cast-selector-receiver",name:FSa()});return a},eTa=function(){var a=dTa(),b=b9();
b||(b=$8());return g.db(a,function(c){return b&&I6(b,c.key)?!0:!1})},b9=function(){var a=W8();
if(!a)return null;var b=V8().Gh();return N6(b,a)},aTa=function(a){X8("remote.onCastSessionChange_: "+J6(a));
if(a){var b=b9();if(b&&b.id==a.id){if(u8(b.id,"YouTube TV"),"shortLived"==a.idType&&(a=a.token))e9&&(e9.token=a),(b=c9())&&b.Pz(a)}else b&&f9(),g9(a,1)}else c9()&&f9()},f9=function(){s8()?p8().stopSession():n8("stopSession called before API ready.");
var a=c9();a&&(a.disconnect(1),h9(null))},i9=function(){var a=c9();
return!!a&&3!=a.getProxyState()},X8=function(a){G7("remote",a)},V8=function(){if(!j9){var a=g.Ga("yt.mdx.remote.screenService_");
j9=a?new S8(a):null}return j9},W8=function(){return g.Ga("yt.mdx.remote.currentScreenId_")},fTa=function(a){g.Fa("yt.mdx.remote.currentScreenId_",a,void 0)},gTa=function(){return g.Ga("yt.mdx.remote.connectData_")},Z8=function(a){g.Fa("yt.mdx.remote.connectData_",a,void 0)},c9=function(){return g.Ga("yt.mdx.remote.connection_")},h9=function(a){var b=c9();
Z8(null);a||fTa("");g.Fa("yt.mdx.remote.connection_",a,void 0);U8&&(g.Ab(U8,function(c){c(a)}),U8.length=0);
b&&!a?F6("yt-remote-connection-change",!1):!b&&a&&F6("yt-remote-connection-change",!0)},$8=function(){var a=g.Az();
if(!a)return null;var b=V8();if(!b)return null;b=b.Gh();return N6(b,a)},g9=function(a,b){W8();
b9()&&b9();if(k9)e9=a;else{fTa(a.id);var c=g.Ga("yt.mdx.remote.enableConnectWithInitialState_")||!1;a=new L8(T8,a,a9(),c);a.connect(b,gTa());a.subscribe("beforeDisconnect",function(d){F6("yt-remote-before-disconnect",d)});
a.subscribe("beforeDispose",function(){c9()&&(c9(),h9(null))});
a.subscribe("browserChannelAuthError",function(){var d=b9();d&&"shortLived"==d.idType&&(s8()?p8().handleBrowserChannelAuthError():n8("refreshLoungeToken called before API ready."))});
h9(a)}},bTa=function(){var a=$8();
a?(X8("Resume connection to: "+J6(a)),g9(a,0)):(S6(),GSa(),X8("Skipping connecting because no session screen found."))},$Sa=function(){var a=a9();
if(g.Rb(a)){a=Q6();var b=g.xz("yt-remote-session-name")||"",c=g.xz("yt-remote-session-app")||"";a={device:"REMOTE_CONTROL",id:a,name:b,app:c,mdxVersion:3};g.Fa("yt.mdx.remote.channelParams_",a,void 0)}},a9=function(){return g.Ga("yt.mdx.remote.channelParams_")||{}},l9=function(a,b,c){g.G.call(this);
var d=this;this.l=a;this.G=b;this.Qb=c;this.events=new g.ZM(this);this.Z=this.events.N(this.G,"onVolumeChange",function(e){hTa(d,e)});
this.C=!1;this.suggestion=null;this.I=new g.dK(64);this.i=new g.K(this.gM,500,this);this.u=new g.K(this.hM,1E3,this);this.L=new Y6(this.vW,0,this);this.B={};this.U=new g.K(this.PM,1E3,this);this.J=new Z6(this.seekTo,1E3,this);this.ea=g.Ha;g.J(this,this.events);this.events.N(b,"onCaptionsTrackListChanged",this.rT);this.events.N(b,"captionschanged",this.AS);this.events.N(b,"captionssettingschanged",this.nM);this.events.N(b,"videoplayerreset",this.mz);this.events.N(b,"mdxautoplaycancel",function(){d.Qb.wI()});
a=this.Qb;a.isDisposed();a.subscribe("proxyStateChange",this.fL,this);a.subscribe("remotePlayerChange",this.Rv,this);a.subscribe("remoteQueueChange",this.mz,this);a.subscribe("previousNextChange",this.cL,this);a.subscribe("nowAutoplaying",this.WK,this);a.subscribe("autoplayDismissed",this.zK,this);g.J(this,this.i);g.J(this,this.u);g.J(this,this.L);g.J(this,this.U);g.J(this,this.J);this.nM();this.mz();this.Rv()},hTa=function(a,b){if(m9(a)){a.Qb.unsubscribe("remotePlayerChange",a.Rv,a);
var c=Math.round(b.volume);b=!!b.muted;var d=E8(a.Qb);if(c!==d.volume||b!==d.muted)a.Qb.setVolume(c,b),a.U.start();a.Qb.subscribe("remotePlayerChange",a.Rv,a)}},iTa=function(a){a.Sb(0);
a.i.stop();a.Pb(new g.dK(64))},n9=function(a,b){if(m9(a)&&!a.C){var c=null;
b&&(c={style:a.G.getSubtitlesUserSettings()},g.Yb(c,b));a.Qb.LG(a.G.getVideoData(1).videoId,c);a.B=E8(a.Qb).trackData}},o9=function(a,b){var c=a.G.getPlaylist();
if(null===c||void 0===c?0:c.listId){var d=c.index;var e=c.listId.toString()}c=a.G.getVideoData(1);a.Qb.playVideo(c.videoId,b,d,e,c.playerParams,c.Oa,GQa(c));a.Pb(new g.dK(1))},jTa=function(a,b){if(b){var c=a.G.getOption("captions","tracklist",{vJ:1});
c&&c.length?(a.G.setOption("captions","track",b),a.C=!1):(a.G.loadModule("captions"),a.C=!0)}else a.G.setOption("captions","track",{})},m9=function(a){return E8(a.Qb).videoId===a.G.getVideoData(1).videoId},p9=function(){g.V.call(this,{D:"div",
K:"ytp-mdx-manual-pairing-popup-dialog",V:{role:"dialog"},S:[{D:"div",K:"ytp-mdx-manual-pairing-popup-dialog-inner-content",S:[{D:"div",K:"ytp-mdx-manual-pairing-popup-title",ra:"\ucf54\ub4dc\ub97c \uc0ac\uc6a9\ud558\uc5ec \uc6f9\uc5d0\uc11c TV\uc5d0 \uc5f0\uacb0\ud558\ub294 \uae30\ub2a5\uc774 \uace7 \uc9c0\uc6d0 \uc911\ub2e8\ub429\ub2c8\ub2e4"},{D:"div",K:"ytp-mdx-manual-pairing-popup-buttons",S:[{D:"button",Ea:["ytp-button","ytp-mdx-manual-pairing-popup-learn-more"],ra:"\uc790\uc138\ud788 \uc54c\uc544\ubcf4\uae30"},
{D:"button",Ea:["ytp-button","ytp-mdx-manual-pairing-popup-ok"],ra:"\ud655\uc778"}]}]}]});this.i=new g.JL(this,250);this.learnMoreButton=this.Da("ytp-mdx-manual-pairing-popup-learn-more");this.okButton=this.Da("ytp-mdx-manual-pairing-popup-ok");g.J(this,this.i);this.N(this.learnMoreButton,"click",this.l);this.N(this.okButton,"click",this.u)},q9=function(){g.V.call(this,{D:"div",
K:"ytp-mdx-popup-dialog",V:{role:"dialog"},S:[{D:"div",K:"ytp-mdx-popup-dialog-inner-content",S:[{D:"div",K:"ytp-mdx-popup-title",ra:"\ub85c\uadf8\uc544\uc6c3\ub418\uc5c8\uc2b5\ub2c8\ub2e4"},{D:"div",K:"ytp-mdx-popup-description",ra:"\uc2dc\uccad\ud55c \ub3d9\uc601\uc0c1\uc774 TV\uc758 \uc2dc\uccad \uae30\ub85d\uc5d0 \ucd94\uac00\ub418\uc5b4 TV \ub9de\ucda4 \ub3d9\uc601\uc0c1\uc5d0 \uc601\ud5a5\uc744 \ubbf8\uce60 \uc218 \uc788\uc2b5\ub2c8\ub2e4. \uc6d0\ud558\uc9c0 \uc54a\uc73c\uba74 \ucde8\uc18c\ud558\uace0 \ucef4\ud4e8\ud130\uc5d0\uc11c YouTube\uc5d0 \ub85c\uadf8\uc778\ud558\uc138\uc694."},
{D:"div",K:"ytp-mdx-privacy-popup-buttons",S:[{D:"button",Ea:["ytp-button","ytp-mdx-privacy-popup-cancel"],ra:"\ucde8\uc18c"},{D:"button",Ea:["ytp-button","ytp-mdx-privacy-popup-confirm"],ra:"\ud655\uc778"}]}]}]});this.i=new g.JL(this,250);this.cancelButton=this.Da("ytp-mdx-privacy-popup-cancel");this.confirmButton=this.Da("ytp-mdx-privacy-popup-confirm");g.J(this,this.i);this.N(this.cancelButton,"click",this.l);this.N(this.confirmButton,"click",this.u)},r9=function(a){g.V.call(this,{D:"div",
K:"ytp-remote",S:[{D:"div",K:"ytp-remote-display-status",S:[{D:"div",K:"ytp-remote-display-status-icon",S:[g.Mra()]},{D:"div",K:"ytp-remote-display-status-text",ra:"{{statustext}}"}]}]});this.api=a;this.i=new g.JL(this,250);g.J(this,this.i);this.N(a,"presentingplayerstatechange",this.l);kTa(this,a.vb())},kTa=function(a,b){if(3===a.api.getPresentingPlayerType()){var c={RECEIVER_NAME:a.api.getOption("remote","currentReceiver").name};
b=g.U(b,128)?g.DI("$RECEIVER_NAME\uc5d0\uc11c \uc624\ub958 \ubc1c\uc0dd",c):b.yc()||g.U(b,4)?g.DI("$RECEIVER_NAME\uc5d0\uc11c \uc7ac\uc0dd \uc911",c):g.DI("$RECEIVER_NAME\uc5d0 \uc5f0\uacb0\ub428",c);a.Sa("statustext",b);a.i.show()}else a.i.hide()},s9=function(a,b){g.UP.call(this,"\uc7ac\uc0dd\ud560 \ud654\uba74:",0,a,b);
this.G=a;this.Sn={};this.N(a,"onMdxReceiversChange",this.C);this.N(a,"presentingplayerstatechange",this.C);this.C()},t9=function(a){g.gN.call(this,a);
this.pj={key:L6(),name:"\uc774 \ucef4\ud4e8\ud130"};this.wh=null;this.subscriptions=[];this.uE=this.Qb=null;this.Sn=[this.pj];this.Om=this.pj;this.od=new g.dK(64);this.SJ=0;this.mf=-1;this.Yr=null;this.Wv=this.My=!1;this.em=this.zs=null;if(!g.xF(this.player.T())&&!g.yF(this.player.T())){a=this.player;var b=g.MM(a);b&&(b=b.jn())&&(b=new s9(a,b),g.J(this,b));b=new r9(a);g.J(this,b);g.WM(a,b.element,4);this.zs=new q9;g.J(this,this.zs);g.WM(a,this.zs.element,4);g.T(this.player.T().experiments,"pair_servlet_deprecation_warning_enabled")&&
!g.T(this.player.T().experiments,"deprecate_pair_servlet_enabled")&&(this.Yr=new p9,g.J(this,this.Yr),g.WM(a,this.Yr.element,4));this.Wv=!!$8();this.My=!!g.xz("yt-remote-manual-pairing-warning-shown")}},u9=function(a){a.em&&(a.player.removeEventListener("presentingplayerstatechange",a.em),a.em=null)},lTa=function(a,b,c){a.od=c;
a.player.Y("presentingplayerstatechange",new g.qI(c,b))},mTa=function(a,b,c){var d=!1;
1===b?d=!a.Wv:2===b&&(d=!a.My);d&&g.sI(c,8)&&(a.player.pauseVideo(),u9(a))},v9=function(a,b){if(b.key!==a.Om.key)if(b.key===a.pj.key)f9();
else{if(a.Yr&&!a.My&&b!==a.pj&&"cast-selector-receiver"!==b.key&&g.PF(a.player.T()))nTa(a);else{var c;(c=!g.T(a.player.T().experiments,"mdx_enable_privacy_disclosure_ui"))||(c=((c=g.O("PLAYER_CONFIG"))&&c.args&&void 0!==c.args.authuser?!0:!(!g.O("SESSION_INDEX")&&!g.O("LOGGED_IN")))||a.Wv||!a.zs);(c?0:g.PF(a.player.T())||g.SF(a.player.T()))&&oTa(a)}a.Om=b;if(!a.player.T().X("disable_mdx_connection_in_mdx_module_for_music_web")||!g.yF(a.player.T())){var d=a.player.getPlaylistId();c=a.player.getVideoData(1);
var e=c.videoId;if(!d&&!e||(2===a.player.getAppState()||1===a.player.getAppState())&&g.T(a.player.T().experiments,"should_clear_video_data_on_player_cued_unstarted"))a=null;else{var f=a.player.getPlaylist();if(f){var h=[];for(var l=0;l<f.length;l++)h[l]=f.ib(l).videoId}else h=[e];f=a.player.getCurrentTime(1);a={videoIds:h,listId:d,videoId:e,playerParams:c.playerParams,clickTrackingParams:c.Oa,index:Math.max(a.player.getPlaylistIndex(),0),currentTime:0===f?void 0:f};(c=GQa(c))&&(a.locationInfo=c)}X8("Connecting to: "+
g.Kh(b));"cast-selector-receiver"==b.key?(Z8(a||null),b=a||null,s8()?p8().setLaunchParams(b):n8("setLaunchParams called before ready.")):!a&&i9()&&W8()==b.key?F6("yt-remote-connection-change",!0):(f9(),Z8(a||null),a=V8().Gh(),(b=N6(a,b.key))&&g9(b,1))}}},oTa=function(a){a.player.vb().yc()?a.player.pauseVideo():(a.em=function(b){mTa(a,1,b)},a.player.addEventListener("presentingplayerstatechange",a.em));
a.zs&&a.zs.bd();c9()||(k9=!0)},nTa=function(a){a.player.vb().yc()?a.player.pauseVideo():(a.em=function(b){mTa(a,2,b)},a.player.addEventListener("presentingplayerstatechange",a.em));
a.Yr&&a.Yr.bd();c9()||(k9=!0)},oRa={"\x00":"\\0",
"\b":"\\b","\f":"\\f","\n":"\\n","\r":"\\r","\t":"\\t","\x0B":"\\x0B",'"':'\\"',"\\":"\\\\","<":"\\u003C"},k7={"'":"\\'"},MQa={uX:"atp",D7:"ska",s6:"que",D4:"mus",C7:"sus",M0:"dsp",N6:"seq",g4:"mic",J_:"dpa",IX:"cds",B4:"mlm"},T6,P6="",fRa=aRa("loadCastFramework")||aRa("loadCastApplicationFramework"),hRa=["pkedcjkdefgpdelpbcmbmeomcjbeemfm","enhhojjnijigcajfphajepfemndkmdlo"];/*

 Copyright The Closure Library Authors.
 SPDX-License-Identifier: Apache-2.0
*/
g.Qa(Y6,g.G);g.k=Y6.prototype;g.k.NO=function(a){this.B=arguments;this.i=!1;this.Ib?this.u=g.Pa()+this.Nf:this.Ib=g.kh(this.C,this.Nf)};
g.k.stop=function(){this.Ib&&(g.C.clearTimeout(this.Ib),this.Ib=null);this.u=null;this.i=!1;this.B=[]};
g.k.pause=function(){++this.l};
g.k.resume=function(){this.l&&(--this.l,!this.l&&this.i&&(this.i=!1,this.I.apply(null,this.B)))};
g.k.va=function(){this.stop();Y6.Yd.va.call(this)};
g.k.OO=function(){this.Ib&&(g.C.clearTimeout(this.Ib),this.Ib=null);this.u?(this.Ib=g.kh(this.C,this.u-g.Pa()),this.u=null):this.l?this.i=!0:(this.i=!1,this.I.apply(null,this.B))};g.w(Z6,g.G);g.k=Z6.prototype;g.k.GG=function(a){this.u=arguments;this.Ib||this.l?this.i=!0:$6(this)};
g.k.stop=function(){this.Ib&&(g.C.clearTimeout(this.Ib),this.Ib=null,this.i=!1,this.u=null)};
g.k.pause=function(){this.l++};
g.k.resume=function(){this.l--;this.l||!this.i||this.Ib||(this.i=!1,$6(this))};
g.k.va=function(){g.G.prototype.va.call(this);this.stop()};a7.prototype.stringify=function(a){return g.C.JSON.stringify(a,void 0)};
a7.prototype.parse=function(a){return g.C.JSON.parse(a,void 0)};var c7=new g.Jf;g.w(jRa,g.kf);g.k=e7.prototype;g.k.Do=null;g.k.pm=!1;g.k.Vs=null;g.k.JF=null;g.k.Es=null;g.k.Os=null;g.k.Hm=null;g.k.Vn=null;g.k.aq=null;g.k.If=null;g.k.tA=0;g.k.Ij=null;g.k.pA=null;g.k.Dm=null;g.k.Ft=-1;g.k.WL=!0;g.k.To=!1;g.k.kB=0;g.k.Bz=null;var mRa={},h7={};g.k=e7.prototype;g.k.setTimeout=function(a){this.u=a};
g.k.PO=function(a){a=a.target;var b=this.Bz;b&&3==g.Gi(a)?b.GG():this.WM(a)};
g.k.WM=function(a){try{if(a==this.If)a:{var b=g.Gi(this.If),c=this.If.l,d=this.If.getStatus();if(g.ie&&!g.ae(10)||g.lg&&!g.$d("420+")){if(4>b)break a}else if(3>b||3==b&&!g.Ri(this.If))break a;this.To||4!=b||7==c||(8==c||0>=d?this.i.rj(3):this.i.rj(2));l7(this);var e=this.If.getStatus();this.Ft=e;var f=g.Ri(this.If);if(this.pm=200==e){4==b&&i7(this);if(this.C){for(a=!0;!this.To&&this.tA<f.length;){var h=nRa(this,f);if(h==h7){4==b&&(this.Dm=4,d7(15),a=!1);break}else if(h==mRa){this.Dm=4;d7(16);a=!1;
break}else m7(this,h)}4==b&&0==f.length&&(this.Dm=1,d7(17),a=!1);this.pm=this.pm&&a;a||(i7(this),j7(this))}else m7(this,f);this.pm&&!this.To&&(4==b?this.i.Yw(this):(this.pm=!1,g7(this)))}else 400==e&&0<f.indexOf("Unknown SID")?(this.Dm=3,d7(13)):(this.Dm=0,d7(14)),i7(this),j7(this)}}catch(l){this.If&&g.Ri(this.If)}finally{}};
g.k.aV=function(a){b7((0,g.D)(this.ZU,this,a),0)};
g.k.ZU=function(a){this.To||(l7(this),m7(this,a),g7(this))};
g.k.nL=function(a){b7((0,g.D)(this.YU,this,a),0)};
g.k.YU=function(a){this.To||(i7(this),this.pm=a,this.i.Yw(this),this.i.rj(4))};
g.k.cancel=function(){this.To=!0;i7(this)};
g.k.hV=function(){this.Vs=null;var a=Date.now();0<=a-this.JF?(2!=this.Os&&this.i.rj(3),i7(this),this.Dm=2,d7(18),j7(this)):qRa(this,this.JF-a)};
g.k.getLastError=function(){return this.Dm};g.k=tRa.prototype;g.k.lB=null;g.k.lh=null;g.k.Cz=!1;g.k.iM=null;g.k.Gx=null;g.k.BD=null;g.k.mB=null;g.k.Pa=null;g.k.bl=-1;g.k.Gt=null;g.k.Vt=null;g.k.connect=function(a){this.mB=a;a=o7(this.i,null,this.mB);d7(3);this.iM=Date.now();var b=this.i.J;null!=b?(this.Gt=b[0],(this.Vt=b[1])?(this.Pa=1,uRa(this)):(this.Pa=2,q7(this))):(C6(a,"MODE","init"),this.lh=new e7(this,void 0,void 0,void 0),this.lh.Do=this.lB,f7(this.lh,a,!1,null,!0),this.Pa=0)};
g.k.JP=function(a){if(a)this.Pa=2,q7(this);else{d7(4);var b=this.i;b.Yj=b.Mm.bl;x7(b,9)}a&&this.rj(2)};
g.k.oC=function(a){return this.i.oC(a)};
g.k.abort=function(){this.lh&&(this.lh.cancel(),this.lh=null);this.bl=-1};
g.k.jf=function(){return!1};
g.k.gL=function(a,b){this.bl=a.Ft;if(0==this.Pa)if(b){try{var c=this.l.parse(b)}catch(d){a=this.i;a.Yj=this.bl;x7(a,2);return}this.Gt=c[0];this.Vt=c[1]}else a=this.i,a.Yj=this.bl,x7(a,2);else if(2==this.Pa)if(this.Cz)d7(7),this.BD=Date.now();else if("11111"==b){if(d7(6),this.Cz=!0,this.Gx=Date.now(),a=this.Gx-this.iM,!g.ie||g.ae(10)||500>a)this.bl=200,this.lh.cancel(),d7(12),p7(this.i,this,!0)}else d7(8),this.Gx=this.BD=Date.now(),this.Cz=!1};
g.k.Yw=function(){this.bl=this.lh.Ft;if(this.lh.pm)0==this.Pa?this.Vt?(this.Pa=1,uRa(this)):(this.Pa=2,q7(this)):2==this.Pa&&((!g.ie||g.ae(10)?!this.Cz:200>this.BD-this.Gx)?(d7(11),p7(this.i,this,!1)):(d7(12),p7(this.i,this,!0)));else{0==this.Pa?d7(9):2==this.Pa&&d7(10);var a=this.i;this.lh.getLastError();a.Yj=this.bl;x7(a,2)}};
g.k.uw=function(){return this.i.uw()};
g.k.isActive=function(){return this.i.isActive()};
g.k.rj=function(a){this.i.rj(a)};g.k=r7.prototype;g.k.Xj=null;g.k.Au=null;g.k.Tg=null;g.k.De=null;g.k.nB=null;g.k.Hx=null;g.k.PH=null;g.k.Zw=null;g.k.Dv=0;g.k.TR=0;g.k.Jf=null;g.k.Vm=null;g.k.yl=null;g.k.fp=null;g.k.Mm=null;g.k.nA=null;g.k.Tr=-1;g.k.RJ=-1;g.k.Yj=-1;g.k.Cr=0;g.k.dr=0;g.k.Uo=8;g.Qa(wRa,g.kf);g.Qa(xRa,g.kf);g.k=r7.prototype;g.k.connect=function(a,b,c,d,e){d7(0);this.nB=b;this.Au=c||{};d&&void 0!==e&&(this.Au.OSID=d,this.Au.OAID=e);this.C?(b7((0,g.D)(this.jI,this,a),100),BRa(this)):this.jI(a)};
g.k.jI=function(a){this.Mm=new tRa(this);this.Mm.lB=this.Xj;this.Mm.l=this.B;this.Mm.connect(a)};
g.k.jf=function(){return 0==this.Pa};
g.k.getState=function(){return this.Pa};
g.k.lL=function(a){this.Vm=null;FRa(this,a)};
g.k.kL=function(){this.yl=null;this.De=new e7(this,this.l,"rpc",this.I);this.De.Do=this.Xj;this.De.kB=0;var a=this.PH.clone();g.lk(a,"RID","rpc");g.lk(a,"SID",this.l);g.lk(a,"CI",this.nA?"0":"1");g.lk(a,"AID",this.Tr);s7(this,a);if(!g.ie||g.ae(10))g.lk(a,"TYPE","xmlhttp"),f7(this.De,a,!0,this.Zw,!1);else{g.lk(a,"TYPE","html");var b=this.De,c=!!this.Zw;b.Os=3;b.Hm=B6(a.clone());pRa(b,c)}};
g.k.gL=function(a,b){if(0!=this.Pa&&(this.De==a||this.Tg==a))if(this.Yj=a.Ft,this.Tg==a&&3==this.Pa)if(7<this.Uo){try{var c=this.B.parse(b)}catch(d){c=null}if(Array.isArray(c)&&3==c.length)if(a=c,0==a[0])a:{if(!this.yl){if(this.De)if(this.De.Es+3E3<this.Tg.Es)u7(this),this.De.cancel(),this.De=null;else break a;w7(this);d7(19)}}else this.RJ=a[1],0<this.RJ-this.Tr&&37500>a[2]&&this.nA&&0==this.dr&&!this.fp&&(this.fp=b7((0,g.D)(this.xS,this),6E3));else x7(this,11)}else null!=b&&x7(this,11);else if(this.De==
a&&u7(this),!g.tc(b))for(a=this.B.parse(b),b=0;b<a.length;b++)c=a[b],this.Tr=c[0],c=c[1],2==this.Pa?"c"==c[0]?(this.l=c[1],this.Zw=c[2],c=c[3],null!=c?this.Uo=c:this.Uo=6,this.Pa=3,this.Jf&&this.Jf.fI(),this.PH=o7(this,this.uw()?this.Zw:null,this.nB),GRa(this)):"stop"==c[0]&&x7(this,7):3==this.Pa&&("stop"==c[0]?x7(this,7):"noop"!=c[0]&&this.Jf&&this.Jf.eI(c),this.dr=0)};
g.k.xS=function(){null!=this.fp&&(this.fp=null,this.De.cancel(),this.De=null,w7(this),d7(20))};
g.k.Yw=function(a){if(this.De==a){u7(this);this.De=null;var b=2}else if(this.Tg==a)this.Tg=null,b=1;else return;this.Yj=a.Ft;if(0!=this.Pa)if(a.pm)if(1==b){b=Date.now()-a.Es;var c=c7;c.dispatchEvent(new wRa(c,a.aq?a.aq.length:0,b,this.Cr));t7(this);this.u.length=0}else GRa(this);else{c=a.getLastError();var d;if(!(d=3==c||7==c||0==c&&0<this.Yj)){if(d=1==b)this.Tg||this.Vm||1==this.Pa||2<=this.Cr?d=!1:(this.Vm=b7((0,g.D)(this.lL,this,a),HRa(this,this.Cr)),this.Cr++,d=!0);d=!(d||2==b&&w7(this))}if(d)switch(c){case 1:x7(this,
5);break;case 4:x7(this,10);break;case 3:x7(this,6);break;case 7:x7(this,12);break;default:x7(this,2)}}};
g.k.kQ=function(a){if(!g.gb(arguments,this.Pa))throw Error("Unexpected channel state: "+this.Pa);};
g.k.dW=function(a){a?d7(2):(d7(1),IRa(this,8))};
g.k.oC=function(a){if(a)throw Error("Can't create secondary domain capable XhrIo object.");a=new g.Ai;a.L=!1;return a};
g.k.isActive=function(){return!!this.Jf&&this.Jf.isActive(this)};
g.k.rj=function(a){var b=c7;b.dispatchEvent(new xRa(b,a))};
g.k.uw=function(){return!(!g.ie||g.ae(10))};
g.k=JRa.prototype;g.k.fI=function(){};
g.k.eI=function(){};
g.k.dI=function(){};
g.k.bC=function(){};
g.k.OI=function(){return{}};
g.k.isActive=function(){return!0};g.k=KRa.prototype;g.k.isEmpty=function(){return 0===this.i.length&&0===this.l.length};
g.k.clear=function(){this.i=[];this.l=[]};
g.k.contains=function(a){return g.gb(this.i,a)||g.gb(this.l,a)};
g.k.remove=function(a){var b=this.i;var c=(0,g.JKa)(b,a);0<=c?(g.kb(b,c),b=!0):b=!1;return b||g.lb(this.l,a)};
g.k.Wg=function(){for(var a=[],b=this.i.length-1;0<=b;--b)a.push(this.i[b]);var c=this.l.length;for(b=0;b<c;++b)a.push(this.l[b]);return a};g.Qa(y7,g.G);g.k=y7.prototype;g.k.SU=function(){this.Nf=Math.min(3E5,2*this.Nf);this.u();this.l&&this.start()};
g.k.start=function(){var a=this.Nf+15E3*Math.random();g.Fq(this.i,a);this.l=Date.now()+a};
g.k.stop=function(){this.i.stop();this.l=0};
g.k.isActive=function(){return this.i.isActive()};
g.k.reset=function(){this.i.stop();this.Nf=5E3};g.Qa(z7,JRa);g.k=z7.prototype;g.k.subscribe=function(a,b,c){return this.u.subscribe(a,b,c)};
g.k.unsubscribe=function(a,b,c){return this.u.unsubscribe(a,b,c)};
g.k.Sf=function(a){return this.u.Sf(a)};
g.k.Y=function(a,b){return this.u.Y.apply(this.u,arguments)};
g.k.dispose=function(){this.Z||(this.Z=!0,g.ef(this.u),NRa(this),g.ef(this.l),this.l=null,this.ea=function(){return""})};
g.k.isDisposed=function(){return this.Z};
g.k.connect=function(a,b,c){if(!this.i||2!=this.i.getState()){this.U="";this.l.stop();this.C=a||null;this.B=b||0;a=this.xa+"/test";b=this.xa+"/bind";var d=new r7(c?c.firstTestResults:null,c?c.secondTestResults:null,this.ya),e=this.i;e&&(e.Jf=null);d.Jf=this;this.i=d;A7(this);if(this.i){d=g.O("ID_TOKEN");var f=this.i.Xj||{};d?f["x-youtube-identity-token"]=d:delete f["x-youtube-identity-token"];this.i.Xj=f}e?(3!=e.getState()&&0==DRa(e)||e.getState(),this.i.connect(a,b,this.I,e.l,e.Tr)):c?this.i.connect(a,
b,this.I,c.sessionId,c.arrayId):this.i.connect(a,b,this.I)}};
g.k.sendMessage=function(a,b){a={_sc:a};b&&g.Yb(a,b);this.l.isActive()||2==(this.i?this.i.getState():0)?this.J.push(a):B7(this)&&(A7(this),CRa(this.i,a))};
g.k.fI=function(){this.l.reset();this.C=null;this.B=0;if(this.J.length){var a=this.J;this.J=[];for(var b=0,c=a.length;b<c;++b)CRa(this.i,a[b])}this.Y("handlerOpened")};
g.k.dI=function(a){var b=2==a&&401==this.i.Yj;4==a||b||this.l.start();this.Y("handlerError",a,b)};
g.k.bC=function(a){if(!this.l.isActive())this.Y("handlerClosed");else if(a)for(var b=0,c=a.length;b<c;++b){var d=a[b].map;d&&this.J.push(d)}};
g.k.OI=function(){var a={v:2};this.U&&(a.gsessionid=this.U);0!=this.B&&(a.ui=""+this.B);0!=this.L&&(a.ui=""+this.L);this.C&&g.Yb(a,this.C);return a};
g.k.eI=function(a){"S"==a[0]?this.U=a[1]:"gracefulReconnect"==a[0]?(this.l.start(),ARa(this.i)):this.Y("handlerMessage",new LRa(a[0],a[1]))};
g.k.Pz=function(a){(this.I.loungeIdToken=a)||this.l.stop();if(this.Aa&&this.i){var b=this.i.Xj||{};a?b["X-YouTube-LoungeId-Token"]=a:delete b["X-YouTube-LoungeId-Token"];this.i.Xj=b}};
g.k.IV=function(){this.l.isActive();0==DRa(this.i)&&this.connect(this.C,this.B)};C7.prototype.B=function(a,b,c,d){b?a(d):a({text:c.responseText})};
C7.prototype.u=function(a,b){a(Error("Request error: "+b.status))};
C7.prototype.C=function(a){a(Error("request timed out"))};var URa=Date.now(),F7=null,I7=Array(50),H7=-1,J7=!1;g.Qa(K7,g.R);K7.prototype.Gh=function(){return this.screens};
K7.prototype.contains=function(a){return!!M6(this.screens,a)};
K7.prototype.get=function(a){return a?N6(this.screens,a):null};
K7.prototype.info=function(a){G7(this.I,a)};g.w(L7,g.R);g.k=L7.prototype;g.k.start=function(){!this.i&&isNaN(this.Ib)&&this.vL()};
g.k.stop=function(){this.i&&(this.i.abort(),this.i=null);isNaN(this.Ib)||(g.gt(this.Ib),this.Ib=NaN)};
g.k.va=function(){this.stop();g.R.prototype.va.call(this)};
g.k.vL=function(){this.Ib=NaN;this.i=g.lt(D7(this.u,"/pairing/get_screen"),{method:"POST",postParams:{pairing_code:this.J},timeout:5E3,onSuccess:(0,g.D)(this.RO,this),onError:(0,g.D)(this.QO,this),onTimeout:(0,g.D)(this.SO,this)})};
g.k.RO=function(a,b){this.i=null;a=b.screen||{};a.dialId=this.B;a.name=this.I;b=-1;this.C&&a.shortLivedLoungeToken&&a.shortLivedLoungeToken.value&&a.shortLivedLoungeToken.refreshIntervalMs&&(a.screenIdType="shortLived",a.loungeToken=a.shortLivedLoungeToken.value,b=a.shortLivedLoungeToken.refreshIntervalMs);this.Y("pairingComplete",new H6(a),b)};
g.k.QO=function(a){this.i=null;a.status&&404==a.status?this.l>=pTa.length?this.Y("pairingFailed",Error("DIAL polling timed out")):(a=pTa[this.l],this.Ib=g.et((0,g.D)(this.vL,this),a),this.l++):this.Y("pairingFailed",Error("Server error "+a.status))};
g.k.SO=function(){this.i=null;this.Y("pairingFailed",Error("Server not responding"))};
var pTa=[2E3,2E3,1E3,1E3,1E3,2E3,2E3,5E3,5E3,1E4];g.Qa(N7,K7);g.k=N7.prototype;g.k.start=function(){M7(this)&&this.Y("screenChange");!g.xz("yt-remote-lounge-token-expiration")&&YRa(this);g.gt(this.i);this.i=g.et((0,g.D)(this.start,this),1E4)};
g.k.add=function(a,b){M7(this);VRa(this,a);O7(this,!1);this.Y("screenChange");b(a);a.token||YRa(this)};
g.k.remove=function(a,b){var c=M7(this);XRa(this,a)&&(O7(this,!1),c=!0);b(a);c&&this.Y("screenChange")};
g.k.lA=function(a,b,c,d){var e=M7(this),f=this.get(a.id);f?(f.name!=b&&(f.name=b,O7(this,!1),e=!0),c(a)):d(Error("no such local screen."));e&&this.Y("screenChange")};
g.k.va=function(){g.gt(this.i);N7.Yd.va.call(this)};
g.k.JQ=function(a){M7(this);var b=this.screens.length;a=a&&a.screens||[];for(var c=0,d=a.length;c<d;++c){var e=a[c],f=this.get(e.screenId);f&&(f.token=e.loungeToken,--b)}O7(this,!b);b&&G7(this.I,"Missed "+b+" lounge tokens.")};
g.k.IQ=function(a){G7(this.I,"Requesting lounge tokens failed: "+a)};g.w(Q7,g.R);g.k=Q7.prototype;g.k.start=function(){var a=parseInt(g.xz("yt-remote-fast-check-period")||"0",10);(this.B=g.Pa()-144E5<a?0:a)?T7(this):(this.B=g.Pa()+3E5,g.wz("yt-remote-fast-check-period",this.B),this.FE())};
g.k.isEmpty=function(){return g.Rb(this.i)};
g.k.update=function(){P7("Updating availability on schedule.");var a=this.I(),b=g.Db(this.i,function(c,d){return c&&!!N6(a,d)},this);
S7(this,b)};
g.k.va=function(){g.gt(this.u);this.u=NaN;this.l&&(this.l.abort(),this.l=null);g.R.prototype.va.call(this)};
g.k.FE=function(){g.gt(this.u);this.u=NaN;this.l&&this.l.abort();var a=$Ra(this);if(D6(a)){var b=D7(this.C,"/pairing/get_screen_availability");this.l=E7(this.C,b,{lounge_token:g.Lb(a).join(",")},(0,g.D)(this.zU,this,a),(0,g.D)(this.yU,this))}else S7(this,{}),T7(this)};
g.k.zU=function(a,b){this.l=null;var c=g.Lb($Ra(this));if(g.yb(c,g.Lb(a))){b=b.screens||[];c={};for(var d=0,e=b.length;d<e;++d)c[a[b[d].loungeToken]]="online"==b[d].status;S7(this,c);T7(this)}else this.Zd("Changing Screen set during request."),this.FE()};
g.k.yU=function(a){this.Zd("Screen availability failed: "+a);this.l=null;T7(this)};
g.k.Zd=function(a){G7("OnlineScreenService",a)};g.Qa(U7,K7);g.k=U7.prototype;g.k.start=function(){this.l.start();this.i.start();this.screens.length&&(this.Y("screenChange"),this.i.isEmpty()||this.Y("onlineScreenChange"))};
g.k.add=function(a,b,c){this.l.add(a,b,c)};
g.k.remove=function(a,b,c){this.l.remove(a,b,c);this.i.update()};
g.k.lA=function(a,b,c,d){this.l.contains(a)?this.l.lA(a,b,c,d):(a="Updating name of unknown screen: "+a.name,G7(this.I,a),d(Error(a)))};
g.k.Gh=function(a){return a?this.screens:g.ob(this.screens,g.Io(this.u,function(b){return!this.contains(b)},this))};
g.k.HG=function(){return g.Io(this.Gh(!0),function(a){return!!this.i.i[a.id]},this)};
g.k.IG=function(a,b,c,d,e,f){var h=this;this.info("getDialScreenByPairingCode "+a+" / "+b);var l=new L7(this.B,a,b,c,d);l.subscribe("pairingComplete",function(m,n){g.ef(l);e(V7(h,m),n)});
l.subscribe("pairingFailed",function(m){g.ef(l);f(m)});
l.start();return(0,g.D)(l.stop,l)};
g.k.TO=function(a,b,c,d){g.lt(D7(this.B,"/pairing/get_screen"),{method:"POST",postParams:{pairing_code:a},timeout:5E3,onSuccess:(0,g.D)(function(e,f){e=new H6(f.screen||{});if(!e.name||dSa(this,e.name)){a:{f=e.name;for(var h=2,l=b(f,h);dSa(this,l);){h++;if(20<h)break a;l=b(f,h)}f=l}e.name=f}c(V7(this,e))},this),
onError:(0,g.D)(function(e){d(Error("pairing request failed: "+e.status))},this),
onTimeout:(0,g.D)(function(){d(Error("pairing request timed out."))},this)})};
g.k.va=function(){g.ef(this.l);g.ef(this.i);U7.Yd.va.call(this)};
g.k.SQ=function(){fSa(this);this.Y("screenChange");this.i.update()};
U7.prototype.dispose=U7.prototype.dispose;g.Qa(X7,g.R);g.k=X7.prototype;g.k.getScreen=function(){return this.B};
g.k.qg=function(a){this.isDisposed()||(a&&(Z7(this,""+a),this.Y("sessionFailed")),this.B=null,this.Y("sessionScreen",null))};
g.k.info=function(a){G7(this.Aa,a)};
g.k.JG=function(){return null};
g.k.TE=function(a){var b=this.i;a?(b.displayStatus=new chrome.cast.ReceiverDisplayStatus(a,[]),b.displayStatus.showStop=!0):b.displayStatus=null;chrome.cast.setReceiverDisplayStatus(b,(0,g.D)(function(){this.info("Updated receiver status for "+b.friendlyName+": "+a)},this),(0,g.D)(function(){Z7(this,"Failed to update receiver status for: "+b.friendlyName)},this))};
g.k.va=function(){this.TE("");X7.Yd.va.call(this)};g.w($7,X7);g.k=$7.prototype;g.k.SE=function(a){if(this.l){if(this.l==a)return;Z7(this,"Overriding cast session with new session object");oSa(this);this.xa=!1;this.U="unknown";this.l.removeUpdateListener(this.ea);this.l.removeMessageListener("urn:x-cast:com.google.youtube.mdx",this.ya)}this.l=a;this.l.addUpdateListener(this.ea);this.l.addMessageListener("urn:x-cast:com.google.youtube.mdx",this.ya);kSa(this,"getMdxSessionStatus")};
g.k.Ur=function(a){this.info("launchWithParams no-op for Cast: "+g.Kh(a))};
g.k.stop=function(){this.l?this.l.stop((0,g.D)(function(){this.qg()},this),(0,g.D)(function(){this.qg(Error("Failed to stop receiver app."))},this)):this.qg(Error("Stopping cast device without session."))};
g.k.TE=function(){};
g.k.va=function(){this.info("disposeInternal");oSa(this);this.l&&(this.l.removeUpdateListener(this.ea),this.l.removeMessageListener("urn:x-cast:com.google.youtube.mdx",this.ya));this.l=null;X7.prototype.va.call(this)};
g.k.kV=function(a,b){if(!this.isDisposed())if(b)if(b=E6(b),g.La(b))switch(a=""+b.type,b=b.data||{},this.info("onYoutubeMessage_: "+a+" "+g.Kh(b)),a){case "mdxSessionStatus":iSa(this,b);break;case "loungeToken":lSa(this,b);break;default:Z7(this,"Unknown youtube message: "+a)}else Z7(this,"Unable to parse message.");else Z7(this,"No data in message.")};
g.k.cJ=function(a,b,c,d){g.gt(this.L);this.L=0;cSa(this.u,this.i.label,a,this.i.friendlyName,(0,g.D)(function(e){e?b(e):0<=d?(Z7(this,"Screen "+a+" appears to be offline. "+d+" retries left."),this.L=g.et((0,g.D)(this.cJ,this,a,b,c,d-1),300)):c(Error("Unable to fetch screen."))},this),c)};
g.k.JG=function(){return this.l};
g.k.UO=function(a){this.isDisposed()||a||(Z7(this,"Cast session died."),this.qg())};g.w(c8,X7);g.k=c8.prototype;g.k.SE=function(a){this.l=a;this.l.addUpdateListener(this.Fa)};
g.k.Ur=function(a){this.Ja=a;this.Z()};
g.k.stop=function(){vSa(this);this.l?this.l.stop((0,g.D)(this.qg,this,null),(0,g.D)(this.qg,this,"Failed to stop DIAL device.")):this.qg()};
g.k.va=function(){vSa(this);this.l&&this.l.removeUpdateListener(this.Fa);this.l=null;X7.prototype.va.call(this)};
g.k.VO=function(a){this.isDisposed()||a||(Z7(this,"DIAL session died."),this.C(),this.C=g.Ha,this.qg())};g.w(g8,X7);g8.prototype.stop=function(){this.qg()};
g8.prototype.SE=function(){};
g8.prototype.Ur=function(){g.gt(this.l);this.l=NaN;var a=N6(this.u.Gh(),this.i.label);a?Y7(this,a):this.qg(Error("No such screen"))};
g8.prototype.va=function(){g.gt(this.l);this.l=NaN;X7.prototype.va.call(this)};g.w(h8,g.R);g.k=h8.prototype;
g.k.init=function(a,b){chrome.cast.timeout.requestSession=3E4;var c=new chrome.cast.SessionRequest(this.L);this.U||(c.dialRequest=new chrome.cast.DialRequest("YouTube"));var d=chrome.cast.AutoJoinPolicy.TAB_AND_ORIGIN_SCOPED;a=a||this.I?chrome.cast.DefaultActionPolicy.CAST_THIS_TAB:chrome.cast.DefaultActionPolicy.CREATE_SESSION;var e=(0,g.D)(this.jU,this);c=new chrome.cast.ApiConfig(c,(0,g.D)(this.hL,this),e,d,a);c.customDialLaunchCallback=(0,g.D)(this.US,this);chrome.cast.initialize(c,(0,g.D)(function(){this.isDisposed()||
(chrome.cast.addReceiverActionListener(this.C),RRa(),this.l.subscribe("onlineScreenChange",(0,g.D)(this.KG,this)),this.u=ySa(this),chrome.cast.setCustomReceivers(this.u,g.Ha,(0,g.D)(function(f){this.Zd("Failed to set initial custom receivers: "+g.Kh(f))},this)),this.Y("yt-remote-cast2-availability-change",j8(this)),b(!0))},this),(0,g.D)(function(f){this.Zd("Failed to initialize API: "+g.Kh(f));
b(!1)},this))};
g.k.NV=function(a,b){i8("Setting connected screen ID: "+a+" -> "+b);if(this.i){var c=this.i.getScreen();if(!a||c&&c.id!=a)i8("Unsetting old screen status: "+this.i.i.friendlyName),k8(this,null)}if(a&&b){if(!this.i){c=N6(this.l.Gh(),a);if(!c){i8("setConnectedScreenStatus: Unknown screen.");return}if("shortLived"==c.idType){i8("setConnectedScreenStatus: Screen with id type to be short lived.");return}a=wSa(this,c);a||(i8("setConnectedScreenStatus: Connected receiver not custom..."),a=new chrome.cast.Receiver(c.uuid?
c.uuid:c.id,c.name),a.receiverType=chrome.cast.ReceiverType.CUSTOM,this.u.push(a),chrome.cast.setCustomReceivers(this.u,g.Ha,(0,g.D)(function(d){this.Zd("Failed to set initial custom receivers: "+g.Kh(d))},this)));
i8("setConnectedScreenStatus: new active receiver: "+a.friendlyName);k8(this,new g8(this.l,a),!0)}this.i.TE(b)}else i8("setConnectedScreenStatus: no screen.")};
g.k.OV=function(a){this.isDisposed()?this.Zd("Setting connection data on disposed cast v2"):this.i?this.i.Ur(a):this.Zd("Setting connection data without a session")};
g.k.XO=function(){this.isDisposed()?this.Zd("Stopping session on disposed cast v2"):this.i?(this.i.stop(),k8(this,null)):i8("Stopping non-existing session")};
g.k.requestSession=function(){chrome.cast.requestSession((0,g.D)(this.hL,this),(0,g.D)(this.CU,this))};
g.k.va=function(){this.l.unsubscribe("onlineScreenChange",(0,g.D)(this.KG,this));window.chrome&&chrome.cast&&chrome.cast.removeReceiverActionListener(this.C);var a=ORa,b=g.Ga("yt.mdx.remote.debug.handlers_");g.lb(b||[],a);g.ef(this.i);g.R.prototype.va.call(this)};
g.k.Zd=function(a){G7("Controller",a)};
g.k.jL=function(a,b){this.i==a&&(b||k8(this,null),this.Y("yt-remote-cast2-session-change",b))};
g.k.gU=function(a,b){if(!this.isDisposed())if(a)switch(a.friendlyName=chrome.cast.unescape(a.friendlyName),i8("onReceiverAction_ "+a.label+" / "+a.friendlyName+"-- "+b),b){case chrome.cast.ReceiverAction.CAST:if(this.i)if(this.i.i.label!=a.label)i8("onReceiverAction_: Stopping active receiver: "+this.i.i.friendlyName),this.i.stop();else{i8("onReceiverAction_: Casting to active receiver.");this.i.getScreen()&&this.Y("yt-remote-cast2-session-change",this.i.getScreen());break}switch(a.receiverType){case chrome.cast.ReceiverType.CUSTOM:k8(this,
new g8(this.l,a));break;case chrome.cast.ReceiverType.DIAL:k8(this,new c8(this.l,a,this.B,this.config_));break;case chrome.cast.ReceiverType.CAST:k8(this,new $7(this.l,a,this.config_));break;default:this.Zd("Unknown receiver type: "+a.receiverType)}break;case chrome.cast.ReceiverAction.STOP:this.i&&this.i.i.label==a.label?this.i.stop():this.Zd("Stopping receiver w/o session: "+a.friendlyName)}else this.Zd("onReceiverAction_ called without receiver.")};
g.k.US=function(a){if(this.isDisposed())return Promise.reject(Error("disposed"));var b=a.receiver;b.receiverType!=chrome.cast.ReceiverType.DIAL&&(this.Zd("Not DIAL receiver: "+b.friendlyName),b.receiverType=chrome.cast.ReceiverType.DIAL);var c=this.i?this.i.i:null;if(!c||c.label!=b.label)return this.Zd("Receiving DIAL launch request for non-clicked DIAL receiver: "+b.friendlyName),Promise.reject(Error("illegal DIAL launch"));if(c&&c.label==b.label&&c.receiverType!=chrome.cast.ReceiverType.DIAL){if(this.i.getScreen())return i8("Reselecting dial screen."),
this.Y("yt-remote-cast2-session-change",this.i.getScreen()),Promise.resolve(new chrome.cast.DialLaunchResponse(!1));this.Zd('Changing CAST intent from "'+c.receiverType+'" to "dial" for '+b.friendlyName);k8(this,new c8(this.l,b,this.B,this.config_))}b=this.i;b.L=a;b.L.appState==chrome.cast.DialAppState.RUNNING?(a=b.L.extraData||{},c=a.screenId||null,d8(b)&&a.loungeToken?a.loungeTokenRefreshIntervalMs?a=sSa(b,{name:b.i.friendlyName,screenId:a.screenId,loungeToken:a.loungeToken,dialId:b.L.receiver.label,
screenIdType:"shortLived"},a.loungeTokenRefreshIntervalMs):(g.os(Error("No loungeTokenRefreshIntervalMs presents in additionalData: "+JSON.stringify(a)+".")),a=tSa(b,c)):a=tSa(b,c)):a=f8(b);return a};
g.k.hL=function(a){var b=this;if(!this.isDisposed()&&!this.I){i8("New cast session ID: "+a.sessionId);var c=a.receiver;if(c.receiverType!=chrome.cast.ReceiverType.CUSTOM){if(!this.i)if(c.receiverType==chrome.cast.ReceiverType.CAST)i8("Got resumed cast session before resumed mdx connection."),c.friendlyName=chrome.cast.unescape(c.friendlyName),k8(this,new $7(this.l,c,this.config_),!0);else{this.Zd("Got non-cast session without previous mdx receiver event, or mdx resume.");return}var d=this.i.i,e=N6(this.l.Gh(),
d.label);e&&I6(e,c.label)&&d.receiverType!=chrome.cast.ReceiverType.CAST&&c.receiverType==chrome.cast.ReceiverType.CAST&&(i8("onSessionEstablished_: manual to cast session change "+c.friendlyName),g.ef(this.i),this.i=new $7(this.l,c,this.config_),this.i.subscribe("sessionScreen",(0,g.D)(this.jL,this,this.i)),this.i.subscribe("sessionFailed",function(){return xSa(b,b.i)}),this.i.Ur(null));
this.i.SE(a)}}};
g.k.WO=function(){return this.i?this.i.JG():null};
g.k.CU=function(a){this.isDisposed()||(this.Zd("Failed to estabilish a session: "+g.Kh(a)),a.code!=chrome.cast.ErrorCode.CANCEL&&k8(this,null),this.Y("yt-remote-cast2-session-failed"))};
g.k.jU=function(a){i8("Receiver availability updated: "+a);if(!this.isDisposed()){var b=j8(this);this.J=a==chrome.cast.ReceiverAvailability.AVAILABLE;j8(this)!=b&&this.Y("yt-remote-cast2-availability-change",j8(this))}};
g.k.KG=function(){this.isDisposed()||(this.u=ySa(this),i8("Updating custom receivers: "+g.Kh(this.u)),chrome.cast.setCustomReceivers(this.u,g.Ha,(0,g.D)(function(){this.Zd("Failed to set custom receivers.")},this)),this.Y("yt-remote-cast2-availability-change",j8(this)))};
h8.prototype.setLaunchParams=h8.prototype.OV;h8.prototype.setConnectedScreenStatus=h8.prototype.NV;h8.prototype.stopSession=h8.prototype.XO;h8.prototype.getCastSession=h8.prototype.WO;h8.prototype.requestSession=h8.prototype.requestSession;h8.prototype.init=h8.prototype.init;h8.prototype.dispose=h8.prototype.dispose;var q8=[];g.k=v8.prototype;
g.k.reset=function(a){this.listId="";this.index=-1;this.videoId="";w8(this);this.volume=-1;this.muted=!1;a&&(this.index=a.index,this.listId=a.listId,this.videoId=a.videoId,this.playerState=a.playerState,this.volume=a.volume,this.muted=a.muted,this.audioTrackId=a.audioTrackId,this.trackData=a.trackData,this.Ak=a.hasPrevious,this.hasNext=a.hasNext,this.J=a.playerTime,this.I=a.playerTimeAt,this.B=a.seekableStart,this.i=a.seekableEnd,this.C=a.duration,this.L=a.loadedTime,this.u=a.liveIngestionTime,this.l=
!isNaN(this.u))};
g.k.yc=function(){return 1==this.playerState};
g.k.isAdPlaying=function(){return 1081==this.playerState};
g.k.Cj=function(a){this.C=isNaN(a)?0:a};
g.k.getDuration=function(){return this.l?this.C+x8(this):this.C};
g.k.clone=function(){return new v8(B8(this))};g.w(D8,g.R);g.k=D8.prototype;g.k.getState=function(){return this.Pa};
g.k.play=function(){F8(this)?(this.i?this.i.play(null,g.Ha,K8(this,"play")):J8(this,"play"),I8(this,1,z8(E8(this))),this.Y("remotePlayerChange")):G8(this,this.play)};
g.k.pause=function(){F8(this)?(this.i?this.i.pause(null,g.Ha,K8(this,"pause")):J8(this,"pause"),I8(this,2,z8(E8(this))),this.Y("remotePlayerChange")):G8(this,this.pause)};
g.k.seekTo=function(a){if(F8(this)){if(this.i){var b=E8(this),c=new chrome.cast.media.SeekRequest;c.currentTime=a;b.yc()||3==b.playerState?c.resumeState=chrome.cast.media.ResumeState.PLAYBACK_START:c.resumeState=chrome.cast.media.ResumeState.PLAYBACK_PAUSE;this.i.seek(c,g.Ha,K8(this,"seekTo",{newTime:a}))}else J8(this,"seekTo",{newTime:a});I8(this,3,a);this.Y("remotePlayerChange")}else G8(this,g.Oa(this.seekTo,a))};
g.k.stop=function(){if(F8(this)){this.i?this.i.stop(null,g.Ha,K8(this,"stopVideo")):J8(this,"stopVideo");var a=E8(this);a.index=-1;a.videoId="";w8(a);H8(this,a);this.Y("remotePlayerChange")}else G8(this,this.stop)};
g.k.setVolume=function(a,b){if(F8(this)){var c=E8(this);if(this.l){if(c.volume!=a){var d=Math.round(a)/100;this.l.setReceiverVolumeLevel(d,(0,g.D)(function(){G7("CP","set receiver volume: "+d)},this),(0,g.D)(function(){this.Zd("failed to set receiver volume.")},this))}c.muted!=b&&this.l.setReceiverMuted(b,(0,g.D)(function(){G7("CP","set receiver muted: "+b)},this),(0,g.D)(function(){this.Zd("failed to set receiver muted.")},this))}else{var e={volume:a,
muted:b};-1!=c.volume&&(e.delta=a-c.volume);J8(this,"setVolume",e)}c.muted=b;c.volume=a;H8(this,c)}else G8(this,g.Oa(this.setVolume,a,b))};
g.k.LG=function(a,b){if(F8(this)){var c=E8(this);a={videoId:a};b&&(c.trackData={trackName:b.name,languageCode:b.languageCode,sourceLanguageCode:b.translationLanguage?b.translationLanguage.languageCode:"",languageName:b.languageName,kind:b.kind},a.style=g.Kh(b.style),g.Yb(a,c.trackData));J8(this,"setSubtitlesTrack",a);H8(this,c)}else G8(this,g.Oa(this.LG,a,b))};
g.k.setAudioTrack=function(a,b){F8(this)?(b=b.getLanguageInfo().getId(),J8(this,"setAudioTrack",{videoId:a,audioTrackId:b}),a=E8(this),a.audioTrackId=b,H8(this,a)):G8(this,g.Oa(this.setAudioTrack,a,b))};
g.k.playVideo=function(a,b,c,d,e,f,h){d=void 0===d?null:d;e=void 0===e?null:e;f=void 0===f?null:f;h=void 0===h?null:h;var l=E8(this),m={videoId:a};void 0!==c&&(m.currentIndex=c);A8(l,a,c||0);void 0!==b&&(y8(l,b),m.currentTime=b);d&&(m.listId=d);e&&(m.playerParams=e);f&&(m.clickTrackingParams=f);h&&(m.locationInfo=g.Kh(h));J8(this,"setPlaylist",m);d||H8(this,l)};
g.k.wz=function(a,b){if(F8(this)){if(a&&b){var c=E8(this);A8(c,a,b);H8(this,c)}J8(this,"previous")}else G8(this,g.Oa(this.wz,a,b))};
g.k.nextVideo=function(a,b){if(F8(this)){if(a&&b){var c=E8(this);A8(c,a,b);H8(this,c)}J8(this,"next")}else G8(this,g.Oa(this.nextVideo,a,b))};
g.k.wI=function(){F8(this)?J8(this,"dismissAutoplay"):G8(this,this.wI)};
g.k.dispose=function(){if(3!=this.Pa){var a=this.Pa;this.Pa=3;this.Y("proxyStateChange",a,this.Pa)}g.R.prototype.dispose.call(this)};
g.k.va=function(){KSa(this);this.u=null;this.B.clear();C8(this,null);g.R.prototype.va.call(this)};
g.k.VE=function(a){if((a!=this.Pa||2==a)&&3!=this.Pa&&0!=a){var b=this.Pa;this.Pa=a;this.Y("proxyStateChange",b,a);if(1==a)for(;!this.B.isEmpty();)b=a=this.B,0===b.i.length&&(b.i=b.l,b.i.reverse(),b.l=[]),a.i.pop().apply(this);else 3==a&&this.dispose()}};
g.k.dU=function(a,b){this.Y(a,b)};
g.k.DS=function(a){if(!a)this.Lv(null),C8(this,null);else if(this.l.receiver.volume){a=this.l.receiver.volume;var b=E8(this),c=Math.round(100*a.level||0);if(b.volume!=c||b.muted!=a.muted)G7("CP","Cast volume update: "+a.level+(a.muted?" muted":"")),b.volume=c,b.muted=!!a.muted,H8(this,b)}};
g.k.Lv=function(a){G7("CP","Cast media: "+!!a);this.i&&this.i.removeUpdateListener(this.J);if(this.i=a)this.i.addUpdateListener(this.J),LSa(this),this.Y("remotePlayerChange")};
g.k.CS=function(a){a?(LSa(this),this.Y("remotePlayerChange")):this.Lv(null)};
g.k.nF=function(){J8(this,"sendDebugCommand",{debugCommand:"stats4nerds "})};
g.k.LS=function(){var a=HSa();a&&C8(this,a)};
g.k.Zd=function(a){G7("CP",a)};g.w(L8,g.R);g.k=L8.prototype;
g.k.connect=function(a,b){if(b){var c=b.listId,d=b.videoId,e=b.videoIds,f=b.playerParams,h=b.clickTrackingParams,l=b.index,m={videoId:d},n=b.currentTime,p=b.locationInfo;b=b.loopMode;void 0!==n&&(m.currentTime=5>=n?0:n);f&&(m.playerParams=f);p&&(m.locationInfo=p);h&&(m.clickTrackingParams=h);c&&(m.listId=c);e&&0<e.length&&(m.videoIds=e.join(","));void 0!==l&&(m.currentIndex=l);this.Aa&&(m.loopMode=b||"LOOP_MODE_OFF");c&&(this.hc.listId=c);this.hc.videoId=d;this.hc.index=l||0;this.hc.state=3;y8(this.hc,
n);this.B="UNSUPPORTED";c=this.Aa?"setInitialState":"setPlaylist";M8("Connecting with "+c+" and params: "+g.Kh(m));this.i.connect({method:c,params:g.Kh(m)},a,UQa())}else M8("Connecting without params"),this.i.connect({},a,UQa());OSa(this)};
g.k.Pz=function(a){this.i.Pz(a)};
g.k.dispose=function(){this.isDisposed()||(g.Fa("yt.mdx.remote.remoteClient_",null,void 0),this.Y("beforeDispose"),N8(this,3));g.R.prototype.dispose.call(this)};
g.k.va=function(){O8(this);Q8(this);P8(this);g.gt(this.J);this.J=NaN;g.gt(this.L);this.L=NaN;this.u=null;g.lu(this.U);this.U.length=0;this.i.dispose();g.R.prototype.va.call(this);this.B=this.I=this.l=this.hc=this.i=null};
g.k.EQ=function(){this.yr(2)};
g.k.IS=function(){M8("Channel opened");this.xa&&(this.xa=!1,P8(this),this.ea=g.et((0,g.D)(function(){M8("Timing out waiting for a screen.");this.yr(1)},this),15E3));
YQa(MRa(this.i),this.Ja)};
g.k.ES=function(){M8("Channel closed");isNaN(this.C)?S6(!0):S6();this.dispose()};
g.k.GS=function(a,b){S6();isNaN(this.Ru())?(b&&"shortLived"==this.ya&&this.Y("browserChannelAuthError",a),M8("Channel error: "+a+" without reconnection"),this.dispose()):(this.xa=!0,M8("Channel error: "+a+" with reconnection in "+this.Ru()+" ms"),N8(this,2))};
g.k.FJ=function(a){if(!this.l||0===this.l.length)return!1;for(var b=g.r(this.l),c=b.next();!c.done;c=b.next())if(!c.value.capabilities.has(a))return!1;return!0};
g.k.HS=function(a){a.params?M8("Received: action="+a.action+", params="+g.Kh(a.params)):M8("Received: action="+a.action+" {}");switch(a.action){case "loungeStatus":a=E6(a.params.devices);this.l=g.Pe(a,function(c){return new G6(c)});
a=!!g.db(this.l,function(c){return"LOUNGE_SCREEN"==c.type});
RSa(this,a);a=this.FJ("mlm");this.Y("multiStateLoopEnabled",a);break;case "loungeScreenDisconnected":g.nb(this.l,function(c){return"LOUNGE_SCREEN"==c.type});
RSa(this,!1);break;case "remoteConnected":var b=new G6(E6(a.params.device));g.db(this.l,function(c){return b?c.id==b.id:!1})||HQa(this.l,b);
break;case "remoteDisconnected":b=new G6(E6(a.params.device));g.nb(this.l,function(c){return b?c.id==b.id:!1});
break;case "gracefulDisconnect":break;case "playlistModified":TSa(this,a);break;case "nowPlaying":VSa(this,a);break;case "onStateChange":USa(this,a);break;case "onAdStateChange":WSa(this,a);break;case "onVolumeChanged":XSa(this,a);break;case "onSubtitlesTrackChanged":SSa(this,a);break;case "nowAutoplaying":YSa(this,a);break;case "autoplayDismissed":this.Y("autoplayDismissed");break;case "autoplayUpNext":this.I=a.params.videoId||null;this.Y("autoplayUpNext",this.I);break;case "onAutoplayModeChanged":this.B=
a.params.autoplayMode;this.Y("autoplayModeChange",this.B);"DISABLED"==this.B&&this.Y("autoplayDismissed");break;case "onHasPreviousNextChanged":ZSa(this,a);break;case "requestAssistedSignIn":this.Y("assistedSignInRequested",a.params.authCode);break;case "onLoopModeChanged":this.Y("loopModeChange",a.params.loopMode);break;default:M8("Unrecognized action: "+a.action)}};
g.k.CV=function(){if(this.u){var a=this.u;this.u=null;this.hc.videoId!=a&&R8(this,"getNowPlaying")}};
g.k.zQ=function(){var a=3;this.isDisposed()||(a=0,isNaN(this.Ru())?B7(this.i)&&isNaN(this.C)&&(a=1):a=2);return a};
g.k.yr=function(a){M8("Disconnecting with "+a);g.Fa("yt.mdx.remote.remoteClient_",null,void 0);O8(this);this.Y("beforeDisconnect",a);1==a&&S6();NRa(this.i,a);this.dispose()};
g.k.xQ=function(){var a=this.hc;this.u&&(a=this.hc.clone(),A8(a,this.u,a.index));return B8(a)};
g.k.PV=function(a){var b=new v8(a);b.videoId&&b.videoId!=this.hc.videoId&&(this.u=b.videoId,g.gt(this.J),this.J=g.et((0,g.D)(this.CV,this),5E3));var c=[];this.hc.listId==b.listId&&this.hc.videoId==b.videoId&&this.hc.index==b.index||c.push("remoteQueueChange");this.hc.playerState==b.playerState&&this.hc.volume==b.volume&&this.hc.muted==b.muted&&z8(this.hc)==z8(b)&&g.Kh(this.hc.trackData)==g.Kh(b.trackData)||c.push("remotePlayerChange");this.hc.reset(a);g.Ab(c,function(d){this.Y(d)},this)};
g.k.bJ=function(){var a=this.i.I.id,b=g.db(this.l,function(c){return"REMOTE_CONTROL"==c.type&&c.id!=a});
return b?b.id:""};
g.k.Ru=function(){var a=this.i;return a.l.isActive()?a.l.l-Date.now():NaN};
g.k.uQ=function(){return this.B||"UNSUPPORTED"};
g.k.vQ=function(){return this.I||""};
g.k.YO=function(){if(!isNaN(this.Ru())){var a=this.i.l;g.Gq(a.i);a.start()}};
g.k.MV=function(a,b){R8(this,a,b);QSa(this)};
g.k.MG=function(){var a=g.zt("SID","")||"",b=g.zt("SAPISID","")||"",c=g.zt("__Secure-3PAPISID","")||"";if(!a&&!b&&!c)return"";a=g.de(g.Wa(a),2);b=g.de(g.Wa(b),2);c=g.de(g.Wa(c),2);return g.de(g.Wa(a+","+b+","+c),2)};
L8.prototype.subscribe=L8.prototype.subscribe;L8.prototype.unsubscribeByKey=L8.prototype.Sf;L8.prototype.getProxyState=L8.prototype.zQ;L8.prototype.disconnect=L8.prototype.yr;L8.prototype.getPlayerContextData=L8.prototype.xQ;L8.prototype.setPlayerContextData=L8.prototype.PV;L8.prototype.getOtherConnectedRemoteId=L8.prototype.bJ;L8.prototype.getReconnectTimeout=L8.prototype.Ru;L8.prototype.getAutoplayMode=L8.prototype.uQ;L8.prototype.getAutoplayVideoId=L8.prototype.vQ;L8.prototype.reconnect=L8.prototype.YO;
L8.prototype.sendMessage=L8.prototype.MV;L8.prototype.getXsrfToken=L8.prototype.MG;L8.prototype.isCapabilitySupportedOnConnectedDevices=L8.prototype.FJ;g.w(S8,K7);g.k=S8.prototype;g.k.Gh=function(a){return this.Me.$_gs(a)};
g.k.contains=function(a){return!!this.Me.$_c(a)};
g.k.get=function(a){return this.Me.$_g(a)};
g.k.start=function(){this.Me.$_st()};
g.k.add=function(a,b,c){this.Me.$_a(a,b,c)};
g.k.remove=function(a,b,c){this.Me.$_r(a,b,c)};
g.k.lA=function(a,b,c,d){this.Me.$_un(a,b,c,d)};
g.k.va=function(){for(var a=0,b=this.i.length;a<b;++a)this.Me.$_ubk(this.i[a]);this.i.length=0;this.Me=null;K7.prototype.va.call(this)};
g.k.ZO=function(){this.Y("screenChange")};
g.k.HT=function(){this.Y("onlineScreenChange")};
U7.prototype.$_st=U7.prototype.start;U7.prototype.$_gspc=U7.prototype.TO;U7.prototype.$_gsppc=U7.prototype.IG;U7.prototype.$_c=U7.prototype.contains;U7.prototype.$_g=U7.prototype.get;U7.prototype.$_a=U7.prototype.add;U7.prototype.$_un=U7.prototype.lA;U7.prototype.$_r=U7.prototype.remove;U7.prototype.$_gs=U7.prototype.Gh;U7.prototype.$_gos=U7.prototype.HG;U7.prototype.$_s=U7.prototype.subscribe;U7.prototype.$_ubk=U7.prototype.Sf;var e9=null,k9=!1,T8=null,U8=null,j9=null,Y8=[];g.w(l9,g.G);g.k=l9.prototype;g.k.va=function(){g.G.prototype.va.call(this);this.i.stop();this.u.stop();this.L.stop();this.ea();var a=this.Qb;a.unsubscribe("proxyStateChange",this.fL,this);a.unsubscribe("remotePlayerChange",this.Rv,this);a.unsubscribe("remoteQueueChange",this.mz,this);a.unsubscribe("previousNextChange",this.cL,this);a.unsubscribe("nowAutoplaying",this.WK,this);a.unsubscribe("autoplayDismissed",this.zK,this);this.Qb=this.l=null};
g.k.jj=function(a,b){for(var c=[],d=1;d<arguments.length;++d)c[d-1]=arguments[d];if(2!=this.Qb.Pa)if(m9(this)){if(!E8(this.Qb).isAdPlaying()||"control_seek"!==a)switch(a){case "control_toggle_play_pause":E8(this.Qb).yc()?this.Qb.pause():this.Qb.play();break;case "control_play":this.Qb.play();break;case "control_pause":this.Qb.pause();break;case "control_seek":this.J.GG(c[0],c[1]);break;case "control_subtitles_set_track":n9(this,c[0]);break;case "control_set_audio_track":this.setAudioTrack(c[0])}}else switch(a){case "control_toggle_play_pause":case "control_play":case "control_pause":c=
this.G.getCurrentTime();o9(this,0===c?void 0:c);break;case "control_seek":o9(this,c[0]);break;case "control_subtitles_set_track":n9(this,c[0]);break;case "control_set_audio_track":this.setAudioTrack(c[0])}};
g.k.AS=function(a){this.L.NO(a)};
g.k.vW=function(a){this.jj("control_subtitles_set_track",g.Rb(a)?null:a)};
g.k.nM=function(){var a=this.G.getOption("captions","track");g.Rb(a)||n9(this,a)};
g.k.Sb=function(a){this.l.Sb(a,this.G.getVideoData().lengthSeconds)};
g.k.rT=function(){g.Rb(this.B)||jTa(this,this.B);this.C=!1};
g.k.fL=function(a,b){this.u.stop();2===b&&this.hM()};
g.k.Rv=function(){if(m9(this)){this.i.stop();var a=E8(this.Qb);switch(a.playerState){case 1080:case 1081:case 1084:case 1085:this.l.mf=1;break;case 1082:case 1083:this.l.mf=0;break;default:this.l.mf=-1}switch(a.playerState){case 1081:case 1:this.Pb(new g.dK(8));this.gM();break;case 1085:case 3:this.Pb(new g.dK(9));break;case 1083:case 0:this.Pb(new g.dK(2));this.J.stop();this.Sb(this.G.getVideoData().lengthSeconds);break;case 1084:this.Pb(new g.dK(4));break;case 2:this.Pb(new g.dK(4));this.Sb(z8(a));
break;case -1:this.Pb(new g.dK(64));break;case -1E3:this.Pb(new g.dK(128,{errorCode:"mdx.remoteerror",errorMessage:"\uc774 \ub3d9\uc601\uc0c1\uc740 \uc6d0\uaca9\uc73c\ub85c \uc7ac\uc0dd\ud560 \uc218 \uc5c6\uc2b5\ub2c8\ub2e4."}))}a=E8(this.Qb).trackData;var b=this.B;(a||b?a&&b&&a.trackName==b.trackName&&a.languageCode==b.languageCode&&a.languageName==b.languageName&&a.kind==b.kind:1)||(this.B=a,jTa(this,a));a=E8(this.Qb);-1===a.volume||Math.round(this.G.getVolume())===a.volume&&this.G.isMuted()===
a.muted||this.U.isActive()||this.PM()}else iTa(this)};
g.k.cL=function(){this.G.Y("mdxpreviousnextchange")};
g.k.mz=function(){m9(this)||iTa(this)};
g.k.WK=function(a){isNaN(a)||this.G.Y("mdxnowautoplaying",a)};
g.k.zK=function(){this.G.Y("mdxautoplaycanceled")};
g.k.setAudioTrack=function(a){m9(this)&&this.Qb.setAudioTrack(this.G.getVideoData(1).videoId,a)};
g.k.seekTo=function(a,b){-1===E8(this.Qb).playerState?o9(this,a):b&&this.Qb.seekTo(a)};
g.k.PM=function(){var a=this;if(m9(this)){var b=E8(this.Qb);this.events.jc(this.Z);b.muted?this.G.mute():this.G.unMute();this.G.setVolume(b.volume);this.Z=this.events.N(this.G,"onVolumeChange",function(c){hTa(a,c)})}};
g.k.gM=function(){this.i.stop();if(!this.Qb.isDisposed()){var a=E8(this.Qb);a.yc()&&this.Pb(new g.dK(8));this.Sb(z8(a));this.i.start()}};
g.k.hM=function(){this.u.stop();this.i.stop();var a=this.Qb.u.getReconnectTimeout();2==this.Qb.Pa&&!isNaN(a)&&this.u.start()};
g.k.Pb=function(a){this.u.stop();var b=this.I;if(!g.iK(b,a)){var c=g.U(a,2);c!==g.U(this.I,2)&&this.G.Is(c);this.I=a;lTa(this.l,b,a)}};g.w(p9,g.V);p9.prototype.bd=function(){this.i.show()};
p9.prototype.Cb=function(){this.i.hide()};
p9.prototype.l=function(){g.LJ("https://support.google.com/youtube/answer/7640706")};
p9.prototype.u=function(){F6("mdx-manual-pairing-popup-ok");this.Cb()};g.w(q9,g.V);q9.prototype.bd=function(){this.i.show()};
q9.prototype.Cb=function(){this.i.hide()};
q9.prototype.l=function(){F6("mdx-privacy-popup-cancel");this.Cb()};
q9.prototype.u=function(){F6("mdx-privacy-popup-confirm");this.Cb()};g.w(r9,g.V);r9.prototype.l=function(a){kTa(this,a.state)};g.w(s9,g.UP);s9.prototype.C=function(){var a=this.G.getOption("remote","receivers");a&&1<a.length&&!this.G.getOption("remote","quickCast")?(this.Sn=g.Bb(a,this.i,this),g.VP(this,g.Pe(a,this.i)),a=this.G.getOption("remote","currentReceiver"),a=this.i(a),this.options[a]&&this.Sh(a),this.enable(!0)):this.enable(!1)};
s9.prototype.i=function(a){return a.key};
s9.prototype.aj=function(a){return"cast-selector-receiver"===a?"\uc804\uc1a1...":this.Sn[a].name};
s9.prototype.wf=function(a){g.UP.prototype.wf.call(this,a);this.G.setOption("remote","currentReceiver",this.Sn[a]);this.zb.Cb()};g.w(t9,g.gN);g.k=t9.prototype;
g.k.create=function(){var a=this.player.T(),b=g.vF(a);a={device:"Desktop",app:"youtube-desktop",loadCastApiSetupScript:g.T(a.experiments,"mdx_load_cast_api_bootstrap_script"),enableDialLoungeToken:g.T(a.experiments,"enable_dial_short_lived_lounge_token"),enableCastLoungeToken:g.T(a.experiments,"enable_cast_short_lived_lounge_token")};cTa(b,a);this.subscriptions.push(g.Tu("yt-remote-before-disconnect",this.zS,this));this.subscriptions.push(g.Tu("yt-remote-connection-change",this.kU,this));this.subscriptions.push(g.Tu("yt-remote-receiver-availability-change",
this.eL,this));this.subscriptions.push(g.Tu("yt-remote-auto-connect",this.iU,this));this.subscriptions.push(g.Tu("yt-remote-receiver-resumed",this.hU,this));this.subscriptions.push(g.Tu("mdx-privacy-popup-confirm",this.sV,this));this.subscriptions.push(g.Tu("mdx-privacy-popup-cancel",this.rV,this));this.subscriptions.push(g.Tu("mdx-manual-pairing-popup-ok",this.ER,this));this.eL()};
g.k.load=function(){this.player.cancelPlayback();g.gN.prototype.load.call(this);this.wh=new l9(this,this.player,this.Qb);var a=(a=gTa())?a.currentTime:0;var b=i9()?new D8(c9(),void 0):null;0==a&&b&&(a=z8(E8(b)));0!==a&&this.Sb(a);lTa(this,this.od,this.od);this.player.Sk(6)};
g.k.unload=function(){this.player.Y("mdxautoplaycanceled");this.Om=this.pj;g.hf(this.wh,this.Qb);this.Qb=this.wh=null;g.gN.prototype.unload.call(this);this.player.Sk(5);u9(this)};
g.k.va=function(){g.Uu(this.subscriptions);g.gN.prototype.va.call(this)};
g.k.Kk=function(a,b){for(var c=[],d=1;d<arguments.length;++d)c[d-1]=arguments[d];this.loaded&&this.wh.jj.apply(this.wh,[a].concat(g.v(c)))};
g.k.getAdState=function(){return this.mf};
g.k.AQ=function(){return this.loaded?this.wh.suggestion:null};
g.k.Ak=function(){return this.Qb?E8(this.Qb).Ak:!1};
g.k.hasNext=function(){return this.Qb?E8(this.Qb).hasNext:!1};
g.k.Sb=function(a,b){this.SJ=a||0;this.player.Y("progresssync",a,b);this.player.Ma("onVideoProgress",a)};
g.k.getCurrentTime=function(){return this.SJ};
g.k.getProgressState=function(){var a=E8(this.Qb),b=this.player.getVideoData();return{airingStart:0,airingEnd:0,allowSeeking:g.T(this.player.T().experiments,"web_player_mdx_allow_seeking_change_killswitch")?this.player.kf():!a.isAdPlaying()&&this.player.kf(),clipEnd:b.clipEnd,clipStart:b.clipStart,current:this.getCurrentTime(),displayedStart:-1,duration:a.getDuration(),ingestionTime:a.l?a.u+x8(a):a.u,isAtLiveHead:1>=(a.l?a.i+x8(a):a.i)-this.getCurrentTime(),loaded:a.L,seekableEnd:a.l?a.i+x8(a):a.i,
seekableStart:0<a.B?a.B+x8(a):a.B}};
g.k.nextVideo=function(){this.Qb&&this.Qb.nextVideo()};
g.k.wz=function(){this.Qb&&this.Qb.wz()};
g.k.zS=function(a){1===a&&(this.uE=this.Qb?E8(this.Qb):null)};
g.k.kU=function(){var a=i9()?new D8(c9(),void 0):null;if(a){var b=this.Om;this.loaded&&this.unload();this.Qb=a;this.uE=null;b.key!==this.pj.key&&(this.Om=b,this.load())}else g.ef(this.Qb),this.Qb=null,this.loaded&&(this.unload(),(a=this.uE)&&a.videoId===this.player.getVideoData().videoId&&this.player.cueVideoById(a.videoId,z8(a)));this.player.Y("videodatachange","newdata",this.player.getVideoData(),3)};
g.k.eL=function(){var a=[this.pj],b=a.concat,c=dTa();r8()&&g.xz("yt-remote-cast-available")&&c.push({key:"cast-selector-receiver",name:"Cast..."});this.Sn=b.call(a,c);a=d9()||this.pj;v9(this,a);this.player.Ma("onMdxReceiversChange")};
g.k.iU=function(){var a=d9();v9(this,a)};
g.k.hU=function(){this.Om=d9()};
g.k.sV=function(){this.Wv=!0;u9(this);k9=!1;e9&&g9(e9,1);e9=null};
g.k.rV=function(){this.Wv=!1;u9(this);v9(this,this.pj);this.Om=this.pj;k9=!1;e9=null;this.player.playVideo()};
g.k.ER=function(){this.My=!0;u9(this);g.wz("yt-remote-manual-pairing-warning-shown",!0,2592E3);k9=!1;e9&&g9(e9,1);e9=null};
g.k.bf=function(a,b){switch(a){case "casting":return this.loaded;case "receivers":return this.Sn;case "currentReceiver":return b&&("cast-selector-receiver"===b.key?t8():v9(this,b)),this.loaded?this.Om:this.pj;case "quickCast":return 2===this.Sn.length&&"cast-selector-receiver"===this.Sn[1].key?(b&&t8(),!0):!1}};
g.k.nF=function(){this.Qb.nF()};
g.k.Ki=function(){return!1};
g.k.getOptions=function(){return["casting","receivers","currentReceiver","quickCast"]};g.rN.remote=t9;})(_yt_player);
